### ISSUE TITLE
Secondary resources in CDXJ are not resolved by replay system

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#102]

**Comment by machawk1** [comment]
Our implementation of pywb's binsearch iterator is not done correctly. Reverting to a linear iterator might be good for now for correctness at the expense of efficiency.

**Comment by ibnesayeed** [comment]
What is the issue? Why can't we fix the binary search issue instead? We know linear search wont scale.

**Comment by machawk1** [comment]
_We_ can, @ibnesayeed . Per another ticket, the current implementation is broken. First I plan on fixing it then I plan on making it efficient. Feel free to submit a PR w/ the latter.

**Comment by machawk1** [comment]
Also, please see the weirdness in #6.

**Comment by machawk1** [comment]
@ibnesayeed The issue is that the iterator is halting after the first line in the previous implementation, i.e., not implemented correctly. Mind that we also need to add #99 as a pre-req for binary search to be meaningful. Right now, the CDXJ is not guaranteed to be sorted, so linear produces a correct result but is not scalable.
