### ISSUE TITLE
Embedded resources may not replay correctly if base URI does not have a trailing slash

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#104]
I created a WARC from http://www.cs.odu.edu/~mkelly , which has a relative image of mofro.png. The CDXJ produced from this WARC has a URI-R for the main HTML page of `edu,odu,cs)/~mkelly`. The PNG's URI-R is `edu,odu,cs)/~mkelly/mofro.png`. On replay of `http://www.cs.odu.edu/~mkelly`, the archived copy of `http://www.cs.odu.edu/mofro.png` is requested instead of the archived copy of `http://www.cs.odu.edu/~mkelly/mofro.png`.

Relates to #6.

**Comment by ibnesayeed** [comment]
I think `http://www.cs.odu.edu/~mkelly` should return a `301` at the time of capture and the payload should be returned at `http://www.cs.odu.edu/~mkelly/` which will then request embedded resources with the right references.

**Comment by machawk1** [comment]
TODO: Check if surt lib is removing the final '/'.

**Comment by ibnesayeed** [comment]
Yes, the SURT library removes trailing slash.

```
$ pip install surt
$ python
>>> import surt
>>> surt.surt('http://www.cs.odu.edu/~mkelly')
'edu,odu,cs)/~mkelly'
>>> surt.surt('http://www.cs.odu.edu/~mkelly/')
'edu,odu,cs)/~mkelly'
```

**Comment by ibnesayeed** [comment]
[IAURLCanonicalizer.py](https://github.com/internetarchive/surt/blob/master/surt/IAURLCanonicalizer.py) has a configuration named `path_strip_trailing_slash_unless_empty` that can help resolving this issue if set to `False`, the default is set to `True`.

**Comment by machawk1** [comment]
That appears to get us what we want:
```python
$ pip install surt
$ python
>>> import surt
>>> surt.surt('http://www.cs.odu.edu/~mkelly/')
'edu,odu,cs)/~mkelly'
>>> surt.surt('http://www.cs.odu.edu/~mkelly/', path_strip_trailing_slash_unless_empty=False)
'edu,odu,cs)/~mkelly/'
```

**Comment by machawk1** [comment]
Another minor issue, ipwb relies on pywb's `pywb.utils.canonicalize()` function invoked through remapping locally as `surt()`. We may want to switch back to using the `surt` module directly for this function but the above does have the handy `unsurt()`, which we can continue to use.
