### ISSUE TITLE
Use ipfs.get instead of ipfs.cat?

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#107]
In both the ipwb replay and indexer we use the `cat()` function for IPFS via the `ipfsapi` module to obtain data from ipfs within Python. Would it be better to use `ipfsapi.get()`? Can we `.get()` and return the data from a function? The docs seem to want a path for the data to be stored whereas we want to keep it in memory to mitigate disk i/o.

An advantage might be that `.get()` appears to have built-in compression, at least from the ipfs binary. I have yet to check to verify that this functionality is available in the `ipfsapi` python module.

The `cat()` is meant for display, not retrieval per the ipfs `--help` docs.

**Comment by ibnesayeed** [comment]
> In both the ipwb replay and indexer we use the cat() function for IPFS via the ipfsapi module to obtain data from ipfs within Python.

The `pullFromIPFS` method defined in the indexer (that uses `ipfsapi.cat` method) is not used anywhere. This is a dead code and should be removed.

> Would it be better to use ipfsapi.get()? Can we .get() and return the data from a function?

We are using the right method. To retrieve the data in the form of a string (hence in memory) [ipfsapi.cat](https://ipfs.io/ipns/QmZ86ow1byeyhNRJEatWxGPJKcnQKG7s51MtbHdxxUddTH/Software/Python/ipfsapi/api_ref.html#ipfsapi.Client.cat) is used. corresponding native IPFS CLI `cat` yields the content on STDOUT. On the other hand, [ipfsapi.get](https://ipfs.io/ipns/QmZ86ow1byeyhNRJEatWxGPJKcnQKG7s51MtbHdxxUddTH/Software/Python/ipfsapi/api_ref.html#ipfsapi.Client.get) would download the file in the current working directory and will return nothing useful which is not desired in this case.

**Comment by machawk1** [comment]
@ibnesayeed Thanks for having a look. You're right about `pullFromIPFS`, it should be removed. We should really get some code coverage system in-place to prevent this sort of cruft. I'm going to close this ticket at your advice to remain using `.cat()`.
