### ISSUE TITLE
Integrate repo with a code coverage system

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#109]
e.g., coveralls.

In #107, @ibnesayeed highlighted that `pullFromIPFS()` in indexer.py is no longer used. This would have been detected if we had a system in-place to check this on each PR/merge/commit.

Until we add the coverage system in-place, let's leave the `pullFromIPFS()` definition in-place as an eventual indicator.

**Comment by Kubuxu** [comment]
For go-ipfs and other projects we started using https://codecov.io/, it has much nicer UI/UX and more useful features.

**Comment by machawk1** [comment]
Initial integration with codecov complete. TravisCI spits out the stats but report is not yet updated. Because of this, the codecov badge says unknown. Once we figure out why the reports are not uploaded to codecov and the badge shows the %, this ticket can be closed.
