### ISSUE TITLE
Extraneous characters display in replay possibly introduced by wget

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#121]
I have encountered an issue where extraneous characters are being displayed for simple WARCs in replay. For example, https://github.com/oduwsdl/ipwb/blob/master/ipwb/samples/warcs/froggie.warc.gz shows extraneous 'ac' characters before and '0' after the content. This content is not on the live web capture at http://www.cs.odu.edu/~mkelly/semester/2017_spring/remoteFroggie.html .

The salam WARCs in the core sample data set also have extraneous characters.

Upon further inspection of the froggie warc, this content is inside the WARC, so it's not introduced by ipwb. This may be due to wget's WARC implementation introducing the additional characters, the latter produces with wget 1.18 on macOS.

For froggie I used the command:
`wget -pH --warc-file=froggie http://www.cs.odu.edu/~mkelly/semester/2017_spring/remoteFroggie.html`

**Comment by machawk1** [comment]
Maybe try specifying the encoding?

**Comment by machawk1** [comment]
Also tried simply `wget --warc-file=froggie http://www.cs.odu.edu/~mkelly/semester/2017_spring/remoteFroggie.html` and still received a WARC with extraneous characters. removing the `--warc-file` flag and simply getting the HTML page does not contain these characters.

**Comment by machawk1** [comment]
Adding `--no-warc-compression` does not remedy this issue either.

**Comment by ibnesayeed** [comment]
To me it seems like these padding numbers indicate the size of the payload in hexadecimal form. The one that appears in the beginning of the payload is the number of bytes (in hexadecimal) of the payload to follow and the trailing number is always zero. I don't know why they have it there and whether it is even valid. Looking at the source code of wget might reveal something.

**Comment by machawk1** [comment]
Per discussion via e-mail, this has to do with the `Transfer-Encoding: chunked` HTTP response header. The extra characters are by design and define the chunk sizes. Read the octets before returning the response.
