### ISSUE TITLE
Provide a filter by content-type for URIs locally available interface

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#123]
Otherwise, all images, js, etc. embedded resources are also shown here. Maybe make this a default.

**Comment by ibnesayeed** [comment]
Yes, composite memento counts are more human friendly representation of the collection.

**Comment by machawk1** [comment]
@ibnesayeed Hopefully eventually we will have a better interface or some way to identify seeds but this will help with the verbose output in the meantime.
