### ISSUE TITLE
"AttributeError: 'module' object has no attribute 'getsitepackages'" on replay

### ISSUE THREAD

**Issue by ivilata** [oduwsdl/ipwb#133]
Hi, using commit a3b8406f installed via ``pip`` on a Python 2.7 virtualenv according to instructions, I run ``ipwb index ipwb/samples/warcs/sample-1.warc.gz > test.cdxj``, which seems to work without issued. However, when running ``ipwb replay test.cdxj`` I get this error:

```
(ipwb) ivan[GXS]sax $ ipwb replay test.cdxj 
Executing first-run procedure on provided sample data.
Traceback (most recent call last):
  File "/home/ivan/env/py/ipwb/bin/ipwb", line 11, in <module>
    load_entry_point('ipwb==0.2017.3.6.1411', 'console_scripts', 'ipwb')()
  File "/home/ivan/env/py/ipwb/local/lib/python2.7/site-packages/ipwb/__main__.py", line 18, in main
    args = checkArgs(sys.argv)
  File "/home/ivan/env/py/ipwb/local/lib/python2.7/site-packages/ipwb/__main__.py", line 127, in checkArgs
    results.func(results)
  File "/home/ivan/env/py/ipwb/local/lib/python2.7/site-packages/ipwb/__main__.py", line 49, in checkArgs_replay
    replay.start(cdxjFilePath=args.index)
  File "/home/ivan/env/py/ipwb/local/lib/python2.7/site-packages/ipwb/replay.py", line 460, in start
    ipwbConfig.firstRun()
  File "/home/ivan/env/py/ipwb/local/lib/python2.7/site-packages/ipwb/util.py", line 167, in firstRun
    indexer.indexFileAt(site.getsitepackages()[0] + '/ipwb/' + SAMPLE_WARC,
AttributeError: 'module' object has no attribute 'getsitepackages'
```

Running ``ipwb replay`` without arguments results in the same error.

**Comment by ibnesayeed** [comment]
I am not sure what is causing this issue. However, the CDXJ file should be sorted in order to perform binary search. Try something like this:

```
$ LC_ALL=C sort -u test.cdxj > test-sorted.cdxj
$ ipwb replay test-sorted.cdxj
```

If sorting fixes the issue, it should be documented in the README.

**Comment by machawk1** [comment]
@ibnesayeed The CDXJ should already be sorted prior to being written.

**Comment by machawk1** [comment]
I can reliably replicate this issue in virtualenv but it does not occur when running my system version of Python 2.7 outside of virtualenv. I'll continue to look into what's causing the issue.

**Comment by machawk1** [comment]
https://github.com/pypa/virtualenv/issues/355 appears to be an outstanding issue with virtualenv + site.py

**Comment by machawk1** [comment]
@ibnesayeed That's the goal, but the results prior to the update of including sorting in the indexer were not ordered and thus the binary search could not be used. The solution in-place now is temporary. The indexer has roles beyond indexing that it should not.

**Comment by machawk1** [comment]
Offending line:
`indexer.indexFileAt(site.getsitepackages()[0] + '/ipwb/' + SAMPLE_WARC, ...)`

behaves differently within and outside of virtualenv.

**Outside of virtualenv:**
```py
import site
site.getsitepackages()[0]
'/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages'
```
 
 
**Within virtualenv:**
```py
import site
site.getsitepackages()[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'getsitepackages'
```

**Comment by machawk1** [comment]
Using `ipwb.__file__` looks to get what we need. Verifying this in multiple environments.

**Comment by machawk1** [comment]
@ivilata This is now be fixed and available via source and pypi. Please test it out and let me know if you run into the same or different issues. Thanks again for your bug reports!

**Comment by ivilata** [comment]
I updated via source and the problem seems to have gone away. Thank you for your quick response!
