### ISSUE TITLE
Change sample data to something more relevant

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#135]
If no parameters are supplied to `ipwb replay`, a simple sample capture is used. This sample is @ibnesayeed's @oduwsdl homepage which, while I'm sure is great exposure for him, might be better if changed to something else.

@ibnesayeed What do you suggest as an alternative?

**Comment by ibnesayeed** [comment]
We can use https://github.com/ibnesayeed/acrts/blob/master/assets/acrts.warc.gz

**Comment by machawk1** [comment]
@ibnesayeed That would open a few can of worms re:rewriting. While good for further testing, is there something we can have that's more fundamental and related to THIS project?

**Comment by ibnesayeed** [comment]
At least the page would say it is the ARCHIVED version and the "Self" check will be green. That would be enough description that replay of the primary resource is working while we can work on making other tests green. I would note here that this WARC file only has one capture of each resource for now.

**Comment by machawk1** [comment]
As verbally discussed, a capture of the (currently non-existent) gh-pages for this project would be a suitable "It Works!!" page.

**Comment by ibnesayeed** [comment]
And perhaps we need to capture the page each time we make any changes, so that we have multiple versions.

**Comment by machawk1** [comment]
Now moot, we no longer use sample data when launching the replay system w/o a parameter.
