### ISSUE TITLE
Setup a webhook on a ws-dl machine for testing and deploying new builds in a clean environment

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#152]
As suggested by @ibnesayeed

**Comment by machawk1** [comment]
Related, we should be able to write tests to parallelizing the IPFS cat, add, etc. processes using TravisCI: https://github.com/grosser/parallel_tests/wiki/Distributed-Parallel-Tests-and-Travis-Support

**Comment by ibnesayeed** [comment]
This can be marked done after #426 is fixed.

**Comment by machawk1** [comment]
Marking this as done per @ibnesayeed. #426 was resolved on August 8, 2018.
