### ISSUE TITLE
ipfs config may be located outside of ~/.ipfs

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#153]
In `util.py` we read the `~/.ipfs/config` for both reading the IPFS configuration as well as writing the IPWB settings. Per `> ipfs --help`, the IPFS repository and thus configuration may reside elsewhere, as defined by the `IPFS_PATH` environment variable. By default, this variable is not set.

`readIPFSConfig()` and `writeIPFSConfig()` refer to `~/.ipfs/`without accounting for the potential for the IPFS repository to be elsewhere.

<strike>Strangely, if I `> ipfs init` after setting this variable (`> export IPFS_PATH=~/.ipfs2`), `~/.ipfs/` is created despite the variable's value.</strike> 

_UPDATE: Forgot `export` won't stick between shell sessions. Adding export to `.bashrc` and `ipfs init` produces content in `~/.ipfs2`. Original issue with ipwb still stands._

**Comment by akavel** [comment]
Ouch, just got hit by this :( I have IPFS_PATH set to a directory on a different (bigger) drive, where I want to store the IPFS data, but now I can't test ipwb with this setup :(

**Comment by machawk1** [comment]
@akavel Thanks for reporting in. Replicating your setup/configuration for IPFS will give us a good basis for testing.

**Comment by machawk1** [comment]
@akavel This has now been fixed, so should work with your setup using IPFS_PATH pointing to a different drive.

**Comment by akavel** [comment]
Wowow wow, you guys are turbo fast! Impressive, absolutely never seen project maintainers react with such speed. Really cool, thanks!

Ah yes, and I confirm this is closed :) Though got another one, will report in a new issue :)
