### ISSUE TITLE
Pressing the daemon stop button in the replay UI no longer works

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#155]
```sh
looking for memento)/http:/127.0.0.1:5000/daemon/stop in samples/indexes/sample-encrypted.cdxj
looking for memento)/http:/127.0.0.1:5000/daemon/stop in 
[Errno 21] Is a directory: '/Users/mkelly/PycharmProjects/ipwb/ipwb/'
127.0.0.1 - - [18/May/2017 12:09:16] "GET /memento//http://127.0.0.1:5000/daemon/stop HTTP/1.1" 500 -
````

**Comment by machawk1** [comment]
The original `daemon/status` call in the iframe hits the daemon endpoint fine but for some reason `daemon/stop` hits the memento endpoint.

**Comment by machawk1** [comment]
I can also replicate the behavior from `http://127.0.0.1:5000/daemon/status`.
```sh
commanding daemon with /daemon/status
127.0.0.1 - - [18/May/2017 15:09:19] "GET /daemon/status HTTP/1.1" 200 -
127.0.0.1 - - [18/May/2017 15:09:19] "GET /webui/webui.css HTTP/1.1" 200 -
127.0.0.1 - - [18/May/2017 15:09:19] "GET /webui/webui.js HTTP/1.1" 200 -
127.0.0.1 - - [18/May/2017 15:09:20] "GET /serviceWorker.js HTTP/1.1" 200 -
In show_uri(): serviceWorker.js
showMemento() endpoint with http://127.0.0.1:5000/daemon/stop
127.0.0.1 - - [18/May/2017 15:09:20] "GET /memento/20160305192247/http://127.0.0.1:5000/daemon/stop HTTP/1.1" 404 -
looking for 1,0,0,127:5000)/daemon/stop in samples/indexes/sample-encrypted.cdxj
Resolving request for http://127.0.0.1:5000/daemon/stop at 20160305192247
Found 0 cdxj entrie(s) for 
MEMENTOS:
[]
```

**Comment by machawk1** [comment]
'/daemon/stop' from AJAX causes `/memento/*` route to be taken. curling `/daemon/stop` or hitting it via web browser causes the desired functionality, i.e., the daemon stops. Prefixing the AJAX request with the host also hits the `/memento/*` endpoint.

**Comment by machawk1** [comment]
The localhost IP address is being caught by the regex for the memento endpoint, i.e.,  127.0.0.1:5000->1,0,0,127:5000 (see above). This may need to be tightened.

**Comment by machawk1** [comment]
Still curious as to why `@app.route('/memento/<regex("[0-9]{1,14}"):datetime>/<path:urir>')` captures `http://127.0.0.1:5000/daemon/stop`.

**Comment by machawk1** [comment]
Also, even a hard-coded `window.fetch('http://127.0.0.1:5000/daemon/status')` from AJAX causes the `/memento/` route to be invoked. This occurs after the initial iframe src inclusion of `/daemon/status`, which functions correctly.

**Comment by ibnesayeed** [comment]
I think I know what is happening here. The ServiceWorker is adding the extra padding because only the `/webui/` path is excluded from being rerouted as per https://github.com/oduwsdl/ipwb/blob/master/ipwb/serviceWorker.js#L22. Add more generic exclusions then it should work.

**Comment by machawk1** [comment]
That could be the issue, @ibnesayeed . I'll look further into it.

**Comment by ibnesayeed** [comment]
I would also encourage to send a special request header in all the SW-routed requests to identify them on server and act accordingly. Illustrated below:

```
X-ServiceWorker: ServiceWorker.js:v1
```

**Comment by machawk1** [comment]
Removing the ServiceWorker from the browser, closing, then opening in Incognito (SWs are sometimes too sticky) produced the following when accessing the above hard-coded call to status.

`
commanding daemon with /daemon/status
127.0.0.1 - - [18/May/2017 16:42:29] "GET /daemon/status HTTP/1.1" 200 -
`

**Comment by machawk1** [comment]
@ibnesayeed Why? What does that accomplish?

**Comment by ibnesayeed** [comment]
> `commanding daemon with /daemon/status
127.0.0.1 - - [18/May/2017 16:42:29] "GET /daemon/status HTTP/1.1" 200 -`

As intended, right?

**Comment by machawk1** [comment]
@ibnesayeed Yes. The SW is the cause of this issue and #156. What does adding the `X-ServiceWorker` provide? Thanks for the insight on this ticket.

**Comment by ibnesayeed** [comment]
> Why? What does that accomplish?

There could be many things that can be achieved with this header:

* If the server receives a request without that header then it can decide to send a page that would install the SW
* If installation fails, a message can be shown to the user that the browser is unsupported
* If possible, server might send a rewritten response as a fallback (which we have no intent of doing in IPWB though)
* If it does receive the header, but the version is old, then it can be upgraded with new logic

**Comment by ibnesayeed** [comment]
Rather than using exclusion like `event.request.url.indexOf('/webui/') === -1`, I would perhaps exclude everything from the same origin as the replay. Something like `event.request.url.split('/')[2] !== document.location.host` instead.

**Comment by machawk1** [comment]
@ibnesayeed What is the significance of the `v1` in the header you proposed?

**Comment by ibnesayeed** [comment]
Don't take it verbatim. It is usually a good idea to version your SW to allow upgrades when logic changes. You can specify any string as version number, preferably in the form of a constant and use that to construct the header value.

**Comment by machawk1** [comment]
SW discussion moved to #157.
