### ISSUE TITLE
Check if version of ipwb being used is current, notify user if not

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#162]
Use version on pypi to determine currency. Recommend running pip --upgrade instead of putting logic to update in ipwb itself, as this could open a security hole.

**Comment by ibnesayeed** [comment]
Make sure that communication failures to the pip server are dealt gracefully.

**Comment by machawk1** [comment]
@ibnesayeed That's the plan. If ipwb can't hit pypi, no new version will be reported as available. The idea here is that ipwb will remain usable on non-Internet connected LANs.
