### ISSUE TITLE
ServiceWorker attempts to process HTML memento if installed upon access

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#198]
Logic exists in the replay system (where?) to check if the ServiceWorker has been installed upon accessing a memento. This would occur if the replay system is started up for the first time and a URI-M is immediately accessed instead of the root page of the replay system.

ipwb current checks if it's installed and if not, redirects to install the SW then back to the originally accessed URI-M. Upon returning to the URI-M, the SW is processing the HTML page (root memento) and attempting to unsuccessfully reroute.

The console looks like this on first access using the above pattern:
![screen shot 2017-06-23 at 3 29 36 pm](https://user-images.githubusercontent.com/2514780/27497477-dbd1f502-5828-11e7-94f4-25b51ed31c3a.png)

and like this on subsequent accesses:
![screen shot 2017-06-23 at 3 30 24 pm](https://user-images.githubusercontent.com/2514780/27497490-ecc2b216-5828-11e7-9bcc-51b52875310f.png)

The errors _only occur_ if the SW is installed upon first access, not if the user navigates from a link on the main replay page.

The issue is likely in checking for `isNavigation = event.request.mode === 'navigate'`. Normally, going from the main replay page to this page would be a navigational event but with the redirection to install the SW then redirecting back, `event.request.mode` is `no-cors`.

This is a minor issue. Replay still works as expected (the attempt to recursively redirect the replay system URI at http://127.0.0.1:5000/memento/20170301192639/http://127.0.0.1:5000/20170301192639/cs.odu.edu/~mkelly/semester/2017_spring/remotefroggie.html fails) but this issue might also come up if a user first installs then accesses a URI, e.g., through following the README instructions.

**Comment by ibnesayeed** [comment]
Since we are sending ServiceWorker version in a request header if the fetch was made from SW, we can simply check for the absence of that header and serve a page to the user that installs SW.

**Comment by machawk1** [comment]
@ibnesayeed We currently do something like that (hence, "where?") but use the condition of `!isNavigation && !isWebUI && !isDaemon` to determine whether we should redirect. This is within the SW fetch event. 

With that in-mind, I tried adding a check for `event.request.headers.get('Server')` within the SW fetch event (`self.addEventListener('fetch', function (event) {`) and the request header does not exist.

Do you know of a request header we can check to see if the SW is installed? Will the complete request from the client (inclusive of all HTTP Request headers) be forwarded onto the SW and available via `event.request`?

**Comment by ibnesayeed** [comment]
Wait, you are mixing something up here. `event.request.headers.get('Server')` is not going to work because `Server` is a response header and you are trying to find it in the `fetch` event's request headers. What I am suggesting here is when you make request to the server from the SW, add a custom request header that looks like `X-ServiceWorker: serviceWorker.js:v1` and on the server-side check if this header is missing then you would know that the request is not initiated by a an SW, hence do the needful (i.e., return a response that installs SW).

**Comment by machawk1** [comment]
We do not currently have an issue with the SW being installed. The logic to check for this is in https://github.com/oduwsdl/ipwb/blob/master/ipwb/webui/webui.js#L145-L172 , which is injected into each memento. The logic to conditionally reroute needs to be in the serviceWorker JS. This is an issue of, once it is initially installed, it need not reroute the URI that invoked it to be installed.

**Comment by machawk1** [comment]
`window.performance.navigation.type` might be a way to take care of the initial installation condition.

**Comment by machawk1** [comment]
The `window` object is not available in the SW. Will need to look for another mechanism.

**Comment by machawk1** [comment]
Another bit of logic we could use is to detect the root memento and if that is triggered in the fetch event, don't reroute.

```js
var isRootMemento = event.request.url === event.request.referrer
```

This should work for other instances as well, even when a new SW has not just been installed and the page reloaded.
