### ISSUE TITLE
Logo Ideas

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#21]
We have briefly discussed this before, @ibnesayeed but here can be a place to enumerate the various ideas for an ipwb logo.
* OpenWayback clock + ipfs cube merged
* Others?

**Comment by ibnesayeed** [comment]
* Clock + Cube
* Clocks on three cube faces
* Cube on clock face
* Solar system on clock face

**Comment by machawk1** [comment]
@ibnesayeed Which clock? OpenWayback? Memento? Another?

**Comment by ibnesayeed** [comment]
Memento clock face is what I meant, is there a clock associated with OWB?

**Comment by machawk1** [comment]
Yes:
![images](https://cloud.githubusercontent.com/assets/2514780/15522371/f855f03c-21df-11e6-827c-afea35858893.png)
What does Memento have to do with ipwb?

**Comment by ibnesayeed** [comment]
Oh, I didn't notice those clock hands in that logo before. The clock face would be symbolizing the aspect of time, not particularly Memento.

**Comment by machawk1** [comment]
How about something like this, @ibnesayeed ?

![interplanetarywayback](https://cloud.githubusercontent.com/assets/2514780/15728712/4f148da0-282c-11e6-8305-a662bc803199.png)

**Comment by ibnesayeed** [comment]
I liked it!
