### ISSUE TITLE
Host and port are hard-coded

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#22]
The README now supplies a command to specify the ipfs daemon to use a different port. There is no guarantee that it will be at localhost and the default port but this data is hard-coded into `indexer.py`. Parameterize these values to be customizable at runtime for `indexer.py`. Also, potentially define these defaults in an external file.

**Comment by ibnesayeed** [comment]
Do you imagine more parameters that might be passed? If there are more than a couple then it might be a good idea to use some flag library such as [argparse](https://docs.python.org/3/library/argparse.html).

**Comment by machawk1** [comment]
Yes, I do, and I think argparse is the way to go. Our currently logic simply checks for argument count but this ought to be revised to attribute the WARC path to a parameter name (first value w/o a - or -- in argparse setup params). What other arguments do you imagine?

**Comment by ibnesayeed** [comment]
If we are going to use argparse then we don't have to worry about all the possible arguments just yet, we can add more arguments as we need them. Since the order of the arguments doesn't matter, it wont brake anything.

**Comment by machawk1** [comment]
Because ipwb can be installed via source or pip, it's probably best to store a config elsewhere on the system. ~/.ipfs/config is JSON. From there, we can read the IPFS API (and other IPFS) ports but potentially also extend it with ipwb options. Currently, there are also other entries for things related to but not core to ipfs like ipns, so it wouldn't be too far fetched to also store ipwb settings there for the ipwb replay script to r/w.

**Comment by machawk1** [comment]
This is also now causing false positives in the check for the daemon status in #147 . At the very least as a smart default, the replay system ought to consult the ~/.ipfs/config to override the hard-coded 5000 and 5001 values in ipwb.

**Comment by ibnesayeed** [comment]
Should this ticket be closed now?

**Comment by machawk1** [comment]
@ibnesayeed I am testing with some additional host/port supplied by the user to ensure they are used. If it works, I will close this ticket per #400.
