### ISSUE TITLE
Logic for latest version does not account for versions deployed from 12-1am

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#221]
The current version of ipwb is InterPlanetary Wayback 0.2017.07.04.0020.

`runningLatestIPWB()` in util.py currently performs a pretty naive version check by first fetching the version from pypi (which unfortunately assumes it's up and available!), then sanitizes the currently installed version via:
`currentVersion = ipwbVersion.replace('.0', '.')`

For the date-based format we used for versioning, this works for all fields except the last, which sanitizes to 0.2017.7.4.020. Because this is != to the exact version string (remember: naive!), the currently installed version is out of date. This will only occur when the version is 0.X.Y.Z.0000-0.X.Y.Z.0059, i.e., 12am-1am inclusive of the first and exclusive of the second.

To continue with the naïveté until the checking gets smarter, check for one or more zeros to be replaced in the sanitization process. A simple regex might be in-order.

**Comment by ibnesayeed** [comment]
How about converting datetime to Unix timestamp before comparing?
