### ISSUE TITLE
Print complete usage help even when IPFS is not installed

### ISSUE THREAD

**Issue by ibnesayeed** [oduwsdl/ipwb#232]
Currently, when running any `ipwb` commands, it shows the following message if IPFS is not installed locally:

```
IPFS config not found.
Have you installed ipfs and run ipfs init?
```

This is not the desired behavior because User might want to connect to a remotely running IPFS daemon. This message should only be shown when the command that was run actually needs to access an IPFS endpoint which is not supplied as an argument and does not exist locally.

**Comment by machawk1** [comment]
@ibnesayeed I cannot replicate this message. Can you give more details on your setup?

**Comment by ibnesayeed** [comment]
Perhaps, because you already have the IPFS config file in your system. Try running it in a container to replicate the issue.

**Comment by machawk1** [comment]
@ibnesayeed I was able to replicate your errors when I nuked my local ~/.ipfs directory. The primary use case is to hit the local daemon but I will keep this open for the sake of connecting to remote daemons in the future.

**Comment by ibnesayeed** [comment]
At the moment it is not even showing help messages which is frustrating.

**Comment by machawk1** [comment]
@ibnesayeed Did you `ipfs init`? We may want to specify this explicitly in the README.

Also note that ipwb stores its config information in the ipfs config.

**Comment by ibnesayeed** [comment]
> Did you ipfs init? We may want to specify this explicitly in the README.

This assumes that `ipfs` utility must be installed on the machine. If the IPFS daemon is supplied at run time then there should be no need to keep any traces of IPFS in the system.

**Comment by machawk1** [comment]
I agree, it would be a better setup to allow access to a remote daemon. However, the README currently says, "The InterPlanetary Filesystem (ipfs) daemon must be installed and running before starting ipwb".

There are a few other tickets that are in the same spirit of not requiring a daemon, e.g., using js-ipfs only for fetching from IPFS without pushing anything.

**Comment by ibnesayeed** [comment]
> Also note that ipwb stores its config information in the ipfs config.

Unless there is a good reason for this, I would call it a very bad choice. Once possibility of a danger is that it can be overwritten by IPFS on updates. Additionally, it might add something in the config file that IPFS daemon may not be happy about it.

**Comment by machawk1** [comment]
@ibnesayeed I believe that was a design your that we spoke about and you originally approved of. ;)

The config is just JSON, so if an extra field breaks the daemon, that seems like a parsing problem for the daemon.

I think storing the ipwb config in the ipfs config is a swell design decision. Can you suggest a better place?

**Comment by ibnesayeed** [comment]
> I believe that was a design your that we spoke about and you originally approved of. ;)

I don't recall that, but if I did, I was not thoughtful enough.

> The config is just JSON, so if an extra field breaks the daemon, that seems like a parsing problem for the daemon.

The point is, we don't know how the config file is used and updated by the IPFS utility. It is a config file of another app that does not belong to us, so adding anything there could be a danger for both that tool and ours.

> I think storing the ipwb config in the ipfs config is a swell design decision.

I would disagree here because IPFS is a dependency as a service, not necessarily a local service. Which means, no IPFS related installations are mandatory.

> Can you suggest a better place?

Yes, `~/.ipwb/config.json` please.

**Comment by machawk1** [comment]
@ibnesayeed That's not a bad idea for a location other than littering the user's home directory.

Can you suggest anything else we might store there, perhaps previously processed CDXJs?

**Comment by ibnesayeed** [comment]
> Can you suggest anything else we might store there, perhaps previously processed CDXJs?

Well, any state information can go in a config file such as when the utility was last updated, status of indexing and stuff like that. However, I really don't see a pressing need of a config file, unless necessary, if good defaults are chosen.

**Comment by machawk1** [comment]
Calls to `readIPFSConfig()` in util.py generate the error and immediate exit. Trace to calling this method is dependent on command used, I believe.

**Comment by machawk1** [comment]
- [ ] `ipwb`
- [ ] `ipwb index (with guidance for what to supply)`
- [ ] `ipwb replay` (?)
- [ ] `ipwb loremipsum` (invalid params)
