### ISSUE TITLE
Change default replay listening IP to 0.0.0.0

### ISSUE THREAD

**Issue by ibnesayeed** [oduwsdl/ipwb#235]
In order for the service to be accessible from anywhere other than localhost, the service should be listening to a non-loopback interface, preferably on the multicast address `0.0.0.0`. Currently, it is set to `127.0.0.1` as default and not changeable (which is a bug). While making this change, it is also important to DRY the code around it for so that any run-time change is reflected throughout.

**Comment by machawk1** [comment]
Preliminary tests are showing SW not behaving as expected on 0.0.0.0 compared to localhost or 127.0.0.1.

**Comment by machawk1** [comment]
Closing this issue. I am aware that there are redundancies and some remnant hard-coded references, which will be fixed for (#22).

**Comment by ibnesayeed** [comment]
> Preliminary tests are showing SW not behaving as expected on 0.0.0.0 compared to localhost or 127.0.0.1. SW in Chrome 59 reports, "ServiceWorker registration failed: DOMException: Only secure origins are allowed" per https://www.chromium.org/Home/chromium-security/prefer-secure-origins-for-powerful-new-features .

I am aware of this issue, but it can easily be solved. What hostname is being reported in generated URIs is separate from what interface the daemon is listening on. Supply two configuration options, one for listening interface (that defaults to `0.0.0.0`) and one for the hostname (that defaults to `localhost`).

**Comment by machawk1** [comment]
@ibnesayeed I don't follow. The hostname:port is how the user currently accesses their local replay system. What is the "listening interface"?

**Comment by ibnesayeed** [comment]
> @ibnesayeed I don't follow. The hostname:port is how the user currently accesses their local replay system. What is the "listening interface"?

When a service is running on a machine, it can be reached from a network using an IP address and a port number. Basically, the IP address is to locate the host machine while the port number is to locate a process on that host. However, a host machine can have multiple network interfaces that can be listed using `ifconfig` command in Linux machines. A loop back interface is a special network interface that only works on the same machine and does not listen to any traffic from outside. It is accessible from the hostname `localhost` and often mapped to the IP address `127.0.0.1` (with a masking of `255.0.0.0`). It is possible for an application to specify, which of the many network interfaces available on the machine (along with a specific port) should be used to communicate with it. However, if the application wants to listen to all the network interfaces, it can use another special interface available at `0.0.0.0`.

Hostname is just a way to map a name to an IP address, but the application internally not listens on a hostname, instead it listens on an IP address + Port number combination. Ideally, generated URIs should use a customizable hostname (default to `localhost`), but `app.run()` method should use an IP address as host (default to `0.0.0.0`). We need two separate flags to set these two individually and one flag for port number. Without this isolation, it would be difficult to use IPWB behind a reverse proxy or in a container.

**Comment by machawk1** [comment]
@ibnesayeed Thanks for the clarification!

The flags to customize these values is not yet supported per #22.

If `app.run()` uses 0.0.0.0 as the host, the SW fails to register.

**Comment by ibnesayeed** [comment]
> If app.run() uses 0.0.0.0 as the host, the SW fails to register.

That is understandable, because you might be serving resources at http://0.0.0.0:5000/ which is not the way to go. The interface `0.0.0.0` is not a valid interface from the client's perspective, it is internal to the service. The service should not tell the world that it is listening to the traffic at `0.0.0.0`, instead it can tell it is listening on `localhost` or any other hostname or IP address as configured.

**Comment by ibnesayeed** [comment]
I think, this issue should be reopened because it is not resolved yet.

**Comment by machawk1** [comment]
@ibnesayeed I'm still trying to figure out how to implement this.

TODO:
- [ ] Use localhost, not an IP address (e.g., 127.0.0.1, 0.0.0.0) for users to access the web interface from a browser.
- [ ] From within the ipwb replay code, request resource representations (e.g., the ipwb logo) via 0.0.0.0

That second TODO doesn't seem correct...maybe. I am thinking my confusion is in requests from the python code using `url.request('http://0.0.0.0:5000/logo.png')` compared to serving the HTML with:
```
<html>
<img src="http://localhost:5000/logo.png" />
</html>
```

That way, the SW will use localhost.

**Comment by ibnesayeed** [comment]
I think, the solution is far simpler than you might think. Keep using all the host and port configurations to report in logs or to rewrite URLs, but always listen on the interface `0.0.0.0` in your `app.run()`. Basically, you can just hard code `app.run(host="0.0.0.0")`. You may use port here from the supplied arguments or environment variable, but keep the host argument as it is.

**Comment by machawk1** [comment]
Ok, I'll try that and perform some testing.

Should the IPFS API use 'localhost' as well?

**Comment by machawk1** [comment]
Hmm, 'localhost' and '0.0.0.0' do not work from within the code to access the daemon HTTP API. Perhaps I don't have the loopback setup in hosts on this machine. '127.0.0.1' works, as previously configured.

**Comment by machawk1** [comment]
Reset my /etc/hosts to 
```
127.0.0.1       localhost
255.255.255.255 broadcasthost
::1 localhost
fe80::1%lo0     localhost
```
and it appears to work. The SW also work as well.

**Comment by ibnesayeed** [comment]
> Should the IPFS API use 'localhost' as well?

It doesn't matter as long as there is a way to specify the location of the IPFS service in IPWB so that it knows where to talk to. In a containerized environment, both IPWB and IPFS will be running in separate containers. IPWB will access it as if it was running on a remote host. Presumably, the official IPFS image already listens on the `0.0.0.0` interface by default. However, if you want to run IPFS locally, it is a good idea to listen to the `0.0.0.0` interface if the intent is to make it accessible from elsewhere.

**Comment by ibnesayeed** [comment]
@machawk1 please have a look at https://github.com/oduwsdl/ipwb/commit/b97d915612f4dd0f2a98617fc504f24583814a31#commitcomment-26167913 in case you missed it.
