### ISSUE TITLE
Shutdown the ipfs daemon more gracefully

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#236]
When stopping the ipfs daemon, ipwb currently (https://github.com/oduwsdl/ipwb/blob/master/ipwb/replay.py#L107) runs a `killall ipfs` command via Python subprocess. go-ipfs introduced an `ipfs shutdown` command in version 0.4.10 per https://ipfs.io/blog/27-go-ipfs-0-4-10/

Leverage this if the version of the daemon ≥ 0.4.10. Checking the daemon version will be critical here, as the killall command may still needing in go-ipfs versions < version 0.4.10. This can be accomplished by performing `ipfs shutdown` in a try then forcibly perform the killall if it fails.

**Comment by ibnesayeed** [comment]
Explicit version comparison may not be necessary and often not future-proof. We can perform a feature detection using exceptions and gracefully execute the fallback.

```
try:
    # run ipfs shutdown
except:
    # run killall ipfs
```

Optionally, if a return value is available after executing the command, that can be used to check whether it was successful.

**Comment by machawk1** [comment]
@ibnesayeed I agree and planned to do exactly that.

**Comment by machawk1** [comment]
Another caveat, ipfs-api is based off of ipfs version 0.4.9, so does not yet have the shutdown command. I need to test whether it will route other arbitrary commands but I am thinking not based on a cursory look of the code. We could use something similar to what we have now via subprocess except instead of `killall`, subprocess `ipfs` with the `shutdown` daemon, though this won't throw an internal except. Rather, we can check the command return code for the time being.
