### ISSUE TITLE
TimeMaps returned do not currently contain the first, last, next, and prev relations

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#255]
Related to #185 and #105

**Comment by ibnesayeed** [comment]
Relations `next` and `prev` do not belong to TimeMaps.

**Comment by machawk1** [comment]
I was loose with the title of this for my own notes while fixing. @ibnesayeed **See the implementation** and tweak in title.

`next` and `prev` were in relation to the "TimeMaps" that are contained in the HTTP response Link header. Is there a better name for this?

**Comment by ibnesayeed** [comment]
That is not called TimeMap and there is no name for it as such.

**Comment by machawk1** [comment]
@ibnesayeed thanks...
