### ISSUE TITLE
IPFS failed on ...

### ISSUE THREAD

**Issue by bobberb** [oduwsdl/ipwb#27]
I can't seem to get this to work. Returns "IPFS failed on [link]" for every input. IPFS daemon is currently working normally.

**Comment by ibnesayeed** [comment]
@bobberb have you configured the `IP` and `PORT` global variables according to your setup? One way to find out the problem would be to log the actual exception after [line 99 in indexer](https://github.com/oduwsdl/ipwb/blob/master/ipwb/indexer.py#L99).

**Comment by bobberb** [comment]
IP and Port are correct as their default. How would I enable this log?

Thanks

**Comment by ibnesayeed** [comment]
> How would I enable this log?

By uncommenting line 100.

**Comment by bobberb** [comment]
Will do, currently on a train at the moment, thank you for the quick
response.

**Comment by ibnesayeed** [comment]
Please let us know how it goes.

**Comment by bobberb** [comment]
Dear Sawood,

Ssh-ed in:

Error is a type error?
Image attached.

**Comment by bobberb** [comment]
http://m.imgur.com/FP64dvS

**Comment by ibnesayeed** [comment]
@machawk1 could you please try replicating this issue on a fresh set up? To me it looks like the `pushToIPFS` is not returning what was expected. One possibility could be some changes in the `ipfsApi` library itself.

**Comment by machawk1** [comment]
I was not able to initially replicate this issue but after upgrading to the latest v0.4.2 from a clean slate, running the [ipfs migration tool](https://github.com/ipfs/fs-repo-migrations/blob/master/run.md), per the CLI directive, I received the same error with a sample WARC: "IPFS failed on {URL} then "Skipping {URL}".

We will need to fix this ASAP, @ibnesayeed . Thanks for reporting this issue, @bobberb .

**Comment by bobberb** [comment]
Happy to help! I was blown away when I read the description. Hopefully
we'll hit that singularity of IPFS+MAIDSAFE et. al.

Let me know if you need any more end-user testing.

**Comment by machawk1** [comment]
@ibnesayeed I am receiving the error at https://github.com/ipfs/go-ipfs/issues/2970 from my daemon but am not yet convinced that this ipwb issue can be attributed to that. @ibnesayeed Could this potentially be related to our move to the combined locator, i.e. header_hash/payload_hash? I'll keep digging on this.

**Comment by ibnesayeed** [comment]
I will be able to look into it after coming back from the conference in a week. I will see if I can give it a go sometime later this week when I am done with my presentations at least.

@machawk1 I don't think that the combined locator would cause this issue, as it was nothing but an alternate serialization of the references.

**Comment by machawk1** [comment]
@ibnesayeed It also looks like the ipfsAPI examples changed to `connect()` from `Client()`. This might be a lead yet echo'ing the response to the call from ipwb in its current state returns an object with an IPFS hash.

**Comment by ibnesayeed** [comment]
I would suggest getting rid of the `ipfsTempPath` temporary file storage and add the file contents directly as a Python object or something similar. Also, I would inspect the response of the `add()` method of the API. It is is returning an array then we need to be careful in finding the proper object in the array to read the hash from.

**Comment by machawk1** [comment]
@ibnesayeed The ipfsAPI add function requires a filename as the parameter. Ideally we would not have to create temp files this way. Any other suggestions on this?

I will look at the response of add but have not been able to nail down the issue. IPFS returns a hash for the file after `add()` yet trips an exception.

**Comment by machawk1** [comment]
`IPFS_API.add` returns a list of dictionaries compared to the previous implementation of simply a dictionary. I have changed the code. Please do a fresh pull or refresh to the latest from pip, @bobberb , and let me know if you encounter this or any other issues.

**Comment by bobberb** [comment]
I am getting HTTP 200 responses in the output, including hashes. However, maybe I do not understand how the program functions, but shouldn't this be uploading the contents of the WARC to the daemon for hosting? I can't seem to access any hashes I run through the ipwb binary.

**Comment by machawk1** [comment]
@bobberb I am checking on this. We may have messed something up on the replay side. Thanks again for testing and the feedback.
