### ISSUE TITLE
URI-R Query String Stripped by Replay

### ISSUE THREAD

**Issue by ibnesayeed** [oduwsdl/ipwb#287]
Looking at the routing code in the `replay.py` it looks like the query string of URI-Rs is not considered wherever `<path:urir>` is matched. This means when looking up for the resource `http://example.com/foo?bar=baz`, the response will be returned for `http://example.com/foo` instead.

Note: This report is based on the quick look at the code. I have not tested it.

**Comment by machawk1** [comment]
Fix with a method from https://github.com/ibnesayeed/linkextractor/blob/master/step5/api/main.py, the query string needs to be re-appended. A simple test case printing out the `<path:urir>` Flask param shows that anything after the `?` in a URI-R is not received by the method.

```py
...
from flask import request
...

@app.route("/api/<path:url>")
def api(url):
    qs = request.query_string.decode("utf-8")
    if qs != "":
        url += "?" + qs
```
