### ISSUE TITLE
Add "timemap" relation when specifying self in a TimeMap

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#293]
An example TimeMap at `http://localhost:5000/timemap/link/http://memento.us` would return a response body like:

```sh
<memento.us/>; rel="original",
<http://localhost:5000/timemap/link/http://memento.us>; rel="self"; type="application/link-format",
<http://localhost:5000/20130202100000/memento.us/>; rel="first memento"; datetime="Sat, 02 Feb 2013 10:00:00 GMT",
<http://localhost:5000/20140114100000/memento.us/>; rel="memento"; datetime="Tue, 14 Jan 2014 10:00:00 GMT",
<http://localhost:5000/20140115101500/memento.us/>; rel="memento"; datetime="Wed, 15 Jan 2014 10:15:00 GMT",
<http://localhost:5000/20161231110000/memento.us/>; rel="memento"; datetime="Sat, 31 Dec 2016 11:00:00 GMT",
<http://localhost:5000/20161231110001/memento.us/>; rel="last memento"; datetime="Sat, 31 Dec 2016 11:00:01 GMT"
```

Disregarding the exclusion of the URI-T for the CDXJ version of the TimeMap (#275), the rel type for self ought to also include `timemap` as define RFC7089 **for Link formatted TimeMaps** (see below). This also applied to CDXJ TimeMap, which ought to use the `self timemap` vs. `timemap` relation difference to distinguish itself from the other version.

**Comment by ibnesayeed** [comment]
I think `!id` serves the purpose well. In JSON-LD they use `@id` for the same.

**Comment by machawk1** [comment]
For reference, the same TM in CDXJ:

```
!context ["http://tools.ietf.org/html/rfc7089"]
!id {"uri": "http://localhost:5000/timemap/cdxj/http://memento.us"}
!keys ["memento_datetime_YYYYMMDDhhmmss"]
!meta {"original_uri": "memento.us/"}
!meta {"timemap_uri": {"link_format": "http://localhost:5000/timemap/link/http://memento.us", "cdxj_format": "http://localhost:5000/timemap/cdxj/http://memento.us"}}
20130202100000 {"uri": "http://localhost:5000/20130202100000/memento.us/", "rel": "first memento", "datetime"="Sat, 02 Feb 2013 10:00:00 GMT"}
20140114100000 {"uri": "http://localhost:5000/20140114100000/memento.us/", "rel": "memento", "datetime"="Tue, 14 Jan 2014 10:00:00 GMT"}
20140115101500 {"uri": "http://localhost:5000/20140115101500/memento.us/", "rel": "memento", "datetime"="Wed, 15 Jan 2014 10:15:00 GMT"}
20161231110000 {"uri": "http://localhost:5000/20161231110000/memento.us/", "rel": "memento", "datetime"="Sat, 31 Dec 2016 11:00:00 GMT"}
20161231110001 {"uri": "http://localhost:5000/20161231110001/memento.us/", "rel": "last memento", "datetime"="Sat, 31 Dec 2016 11:00:01 GMT"}
```

The above highlights another issue in accomplishing this: The two URI-Ts are attributes of the same object, so it would be ambiguous as to what a "rel" value applies to here. Some consideration for the "timemap_uri" !meta should be had.

**Comment by machawk1** [comment]
How about something like this, @ibnesayeed ?


```json
!meta {"timemap_uri": [{"link_format": "http://localhost:5000/timemap/link/http://memento.us", rel:"timemap"}, {"cdxj_format": "http://localhost:5000/timemap/cdxj/http://memento.us", rel: "timemap self"}]}
```

Though on second thought, it seems overly verbose and introduces order (a la the array).

**Comment by ibnesayeed** [comment]
Rel in this case is implicit and the nested object with those keys is in accordance to the LANL's JSON format.

**Comment by machawk1** [comment]
Per further discussion in https://github.com/oduwsdl/memgator/issues/108#issuecomment-348070344, the !id metadata field is sufficient for self-identification instead of the rel="self" that is used in Link format.

@ibnesayeed How would you express multiple TimeMaps with associated date ranges (e.g., LANL's aggregator some time back) in this CDXJ `!meta` field?

**Comment by ibnesayeed** [comment]
> @machawk1: How would you express multiple TimeMaps with associated date ranges (e.g., LANL's aggregator some time back) in this CDXJ !meta field?

We will look for how LANL would encode that info in their JSON TimeMap. Currently, MemGator does not provide pagination support so, it is not something we would worry about just yet. However, if we have, we can simply change the value of the `link_format` and alike keys into an array rather than a string. Alternatively, that value can be a an object instead of an array to accommodate dates as keys.

**Comment by machawk1** [comment]
@ibnesayeed I was thinking in other dimensions beyond date ranges and am looking for a way to translate what would likely be in a rel value in Link format to CDXJ and maintain the URI-T association.

**Comment by ibnesayeed** [comment]
Link format is the bigger issue here as it would pose more limitations than any other format in question while being more ambiguous in many cases. So, you better think about how much information do you really want to encode in that reliably. Later we can talk about parallel encoding in other formats.
