### ISSUE TITLE
"IPFS is likely not installed" on Windows

### ISSUE THREAD

**Issue by akavel** [oduwsdl/ipwb#307]
Got a message like this:
```
C:\dnload\ipfs-etc>ipwb replay
IPFS is likely not installed. See https://ipfs.io/docs/install/
```
though I *do* have IPFS installed and running, and on standard ports.

The message is unfortunately uninformative, so not sure how I could help it find the IPFS. Will try to find it in the sources unless you do it sooner (I just had time to report ATM).

**Comment by machawk1** [comment]
@akavel This condition is tripped at https://github.com/oduwsdl/ipwb/blob/9cc6095bf2aff903a49862081216fdcd7138a9de/ipwb/util.py#L41-L54 by an exception being invoked when the `ipfs --version` command is attempted via the Python subprocess module.

Is the command `ipfs --version` syntactically correct on Windows?

I agree that the message is not helpful and will improve it with this ticket once we can pin down why the exception is being thrown in your setup.

**Comment by akavel** [comment]
Ok; then in such case:

1. Worthy to note, I didn't know from the readme or else that `ipfs` must be in PATH;
2. though, accidentally it actually is (!);
3. although it's not an `ipfs.exe` in PATH, but my custom `ipfs.bat` (more precisely, in the working directory, which implicitly is in PATH on Windows),
4. and it works OK if I run it by hand:

        C:\dnload\ipfs-etc>ipwb replay
        IPFS is likely not installed. See https://ipfs.io/docs/install/
        
        C:\dnload\ipfs-etc>ipfs --version
        ipfs version 0.4.13

5. as Windows usually doesn't need full extension when running something;
6. though it sometimes depends on a particular API used (not sure what's used by *subprocess.call*).
7. Also, it might (or might not) be helpful if I saw some more detailed message from OSError, so I could maybe try to deduce what it's actually trying to do, or otherwise what's the particular hissy fit about between Python, Windows, and me.

**Comment by akavel** [comment]
Hmm, generic Windows "File not found", so I haven't learned much yet:

```
C:\dnload\ipfs-etc>ipwb replay
IPFS is likely not installed. See https://ipfs.io/docs/install/
(<type 'exceptions.WindowsError'>, WindowsError(2, 'Nie mo\xbfna odnale\x9f\xe6 okre\x9clonego pliku'), <traceback object at 0x0000000004F6DD48>)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\ipwb\util.py", line 44, in isDaemonAlive
    subprocess.call(['ipfs', '--version'], stdout=open(devnull, 'wb'))
  File "c:\python27\lib\subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "c:\python27\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "c:\python27\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 2] Nie mo┐na odnalečŠ okreťlonego pliku
```

**Comment by akavel** [comment]
Ok, if I modified it to `subprocess.call('ipfs.bat', ...)`, it seems to work, at least on the console (haven't checked the url yet):

```
C:\dnload\ipfs-etc>\python27\python.exe ipwb/ipwb replay
Executing first-run procedure on provided sample data.
Processing WARC records in salam-home.warc complete
 * Running on http://localhost:5000/ (Press CTRL+C to quit)

```

**Comment by akavel** [comment]
Ok, I started wondering why even you need to check the `ipfs` command, if the function seems to check the web API, and I found the *commandDaemon* func, so I can also add that `killall` is not a command on Windows. Maybe you don't need to check for `ipfs` command outside *commandDaemon* at all?

**Comment by machawk1** [comment]
Hmm, you're right, @akavel. An exception from [ipfsapi](https://github.com/ipfs/py-ipfs-api) might indicate whether the IPFS daemon is installed and running.

I'll need to nuke my ipfs binary and check how ipfsapi reacts when there's no daemon with which to communicate.

Also, it's nice to have your Windows-based perspective on `killall`. There might be a better, more cross-compatible method to accomplish forcefully stopping the daemon.

**Comment by machawk1** [comment]
@akavel I have removed the call to the IPFS binary with the expectation that the call to ipfsapi will invoke its respect exception. This works as expected on my box. Can you pull a fresh copy from the repo and see if you experience the above?

**Comment by akavel** [comment]
Fixed for me. Thanks!
