### ISSUE TITLE
Sample URL from readme doesn't work for me

### ISSUE THREAD

**Issue by akavel** [oduwsdl/ipwb#312]
either ;)  [see also #310, maybe related, maybe not] 

I mean the `http://localhost:5000/http://www.cs.odu.edu/~salam/` &mdash; see below screencast:

![issue-ipwb-sample-readme-url](https://user-images.githubusercontent.com/273837/33781688-e1dd52c8-dc55-11e7-998a-f4a6c974e2be.gif)

```
C:\dnload\ipfs-etc>\python27\python.exe ipwb/ipwb replay
This version of ipwb is outdated. Please run pip install --upgrade ipwb.
Executing first-run procedure on provided sample data.
Processing WARC records in salam-home.warc complete
 * Running on http://localhost:5000/ (Press CTRL+C to quit)
Could not edu,odu,cs)/~salam/ in CDXJ at ipwb/ipwb\samples\indexes\sample-encrypted.cdxj
CDXJ Line: None
Getting CDXJ Lines with http://www.cs.odu.edu/~salam/ in ipwb/ipwb\samples\indexes\sample-encrypted.cdxj
Could not edu,odu,cs)/~salam/ in CDXJ at ipwb/ipwb\samples\indexes\sample-encrypted.cdxj
CDXJ lines with URI-R at http://www.cs.odu.edu/~salam/
[]
Getting CDXJ Lines with http://www.cs.odu.edu/~salam/ in ipwb/ipwb\samples\indexes\sample-encrypted.cdxj
Could not edu,odu,cs)/~salam/ in CDXJ at ipwb/ipwb\samples\indexes\sample-encrypted.cdxj
127.0.0.1 - - [08/Dec/2017 20:19:36] "GET /http://www.cs.odu.edu/~salam/ HTTP/1.1" 404 -
```

**Comment by machawk1** [comment]
This is a multi-fold problem:
* The memento endpoint is no longer at host:port/URI-R (the README needs to be updated)
* The input box (from #313) resolves to the /memento/*/URI-R endpoint. I don't think this is current.

That said, there have been some fixes to ensuring the sample data is loaded more correctly, so clicking on the link in the single memento listing on the main page should work.

**Comment by machawk1** [comment]
http://localhost:5000/http://www.cs.odu.edu/~salam/ is an obsolete URI structure for ipwb, @akavel and has been removed from the README.

**Comment by akavel** [comment]
Hm; I assume you may have wanted to close this issue, instead of #313, and mark the #313 one "pending" instead of this one? I don't think you need my follow-up regarding README. Assuming so, I'll reply in #313 about the search box, so I myself won't get confused ;) Unless I misunderstood, then please clarify. Tx!

**Comment by machawk1** [comment]
Nope, you are correct, @akavel. I meant to close this one. I have re-opened #313, as this ticket is no longer applicable given the URI in question is no longer present in the README.
