### ISSUE TITLE
Replay is broken

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#33]
When we moved to combining the header and payload digest as a single locator string, the replay engine no longer seems to be able to resolve the two digests. This is a fairly major issue, @ibnesayeed 

Using the included demo CDXJ files, this is what I get when I try to access ~salam by clicking on the ipwb-provided link.

![screen shot 2016-09-19 at 1 15 12 pm](https://cloud.githubusercontent.com/assets/2514780/18641574/3a06ba7e-7e6b-11e6-992a-5ffadbec611c.png)

**Comment by ibnesayeed** [comment]
Perhaps the issue is elsewhere and the contents are not being saved in IPFS properly. I would suspect the least that the concatenation of hashes causing any such issue.

**Comment by machawk1** [comment]
The issue was stale sample data, @ibnesayeed . There was no "locator" field in the same cdxj. The sample cdxj still had the breakup of the two hashes as two field values in the cdxj. 

5804130aa8bb9d1f30fff0650cf48623642a3cda

**Comment by ibnesayeed** [comment]
Good catch!
