### ISSUE TITLE
Not getting `Content-Encoding: gzip` in replayed responses

### ISSUE THREAD

**Issue by akavel** [oduwsdl/ipwb#331]
I indexed the [attached .warc.gz](https://github.com/oduwsdl/ipwb/files/1560902/gui-library-for-nim-20171214205947.warc.gz), resulting in the [attached .cdxj (zipped)](https://github.com/oduwsdl/ipwb/files/1560905/gui-library-for-nim.zip). When trying to replay it, I'm getting garbled contents instead of sensible websites. Trying to inspect it with Firefox's console, I don't see the `Content-Encoding: gzip` in the response.

The garbled contents in Firefox seem to look like the raw ungzipped contents from the .warc file indeed, same strings can be seen in both places.

**Comment by akavel** [comment]
The Content-Encoding seems to be present in the IPFS object, so I suppose this is something in the replayer?

```
C:\dnload\ipfs-etc>ipfs cat /ipfs/QmU9SkG1gVK7tAAocVjyMDXjZRyByXbCWRBFC8Ednr4MDc
HTTP/1.1 200 OK
Date: Thu, 07 Dec 2017 22:42:41 GMT
Server: Apache/2.4.18 (Ubuntu)
Set-Cookie: PHPSESSID=n77aff5obt3jto2aiaqul5j5q0; path=/
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Vary: Accept-Encoding
Content-Encoding: gzip
Content-Length: 7068
Content-Type: text/html; charset=utf-8
```

**Comment by ibnesayeed** [comment]
This is something we must look into it carefully. Some web browsers are more forgiving in a way that they might detect a compressed file and decompress it even if the server did not tell it specifically. A few things to be considered when making an action plan.

* While we do read the original `Content-Type` from the archived headers to replay, we currently do not look into the `Content-Encoding` header, which we should.
* There are some well known and wide-spread violations of recommendations about the `Content-Encoding` and `Transfer-Encoding`, so we need to be careful about those.
* We considered some permutations of content encoding, compression, and encryption (whether or not the original content was encoded/compressed) in our research publication and have more experiments planned in this direction.

**Comment by akavel** [comment]
Woohoo! The following patch fixes it for me:

```
diff --git a/ipwb/replay.py b/ipwb/replay.py
index 80cb3b9..9f51a44 100755
--- a/ipwb/replay.py
+++ b/ipwb/replay.py
@@ -608,7 +608,7 @@ def show_uri(path, datetime=None):
                 continue  # Data may have no actually been chunked
             resp.set_data(unchunkedPayload)

-        if k.lower() != "content-type":
+        if k.lower() not in ["content-type", "content-encoding"]:
             k = "X-Archive-Orig-" + k

         resp.headers[k] = v
```

**Comment by ibnesayeed** [comment]
> Woohoo! The following patch fixes it for me:

Yes, that is certainly going to fix it for now. However, as I described above, if we were to supply custom `Content-Encoding` header based on certain approaches, we will have to revisit this.

**Comment by akavel** [comment]
As a user, I prefer a working non-perfect solution now, than a perfect solution in Unspecified Future&trade;; sorry ;)

**Comment by machawk1** [comment]
Your edit has been implemented and merged to master, @akavel. Thanks for your contribution.

**Comment by akavel** [comment]
Thanks!!!

**Comment by ibnesayeed** [comment]
> As a user, I prefer a working non-perfect solution now, than a perfect solution in Unspecified Future™; sorry ;)

That is mostly alright for now, but I provided some background so that it is helpful in future when we decide to change things around this.

Also, please feel free submit PRs when you are confident in your changes so that your contributions are well attributed.

**Comment by akavel** [comment]
Thanks :) I wasn't sure if you don't want to add some tests or something. Also was so small... if you have some "contributors" file, it would be cool if you cared to add me there. Otherwise, whatever. I will maybe think about it next time, but if it means to slow things down too much, I'm ok with patches like that if you're ok too!

**Comment by machawk1** [comment]
@akavel PRs or suggestions for tests are welcomed as well. I will figure out a way to ensure that you get credit for your suggested changes, even if you opt to not submit PRs.

**Comment by ibnesayeed** [comment]
Tests are always welcome, but not necessarily a road blocker at this stage. However, when the project gets bigger or reworked to accommodate things more cleanly (based on what we have learned so far from this rather hacky approach) then tests might be a crucial requirement.

I am generally against adding extra scruff in the repo, so rather than adding a contributors file I would just rely on GitHub's way of showing contributions which is often much more elaborated than a contributors file could be (put aside the burden of actively maintaining it).

**Comment by machawk1** [comment]
https://api.github.com/repos/oduwsdl/ipwb/contributors list the contributors but I think that's based solely on code contributions, so wouldn't be sufficient for include @akavel if automatically generated.

**Comment by ibnesayeed** [comment]
While GitHub does not show non-code contributions in the API or under corresponding tab (because quantifying such things would be difficult), but history of discussions, comments, and code reviews etc. are all present in their respective places.

**Comment by ibnesayeed** [comment]
A custom contributions file is problematic because merely listing names gives an impression that everyone has equal contribution (or more accurately, it does not tell anything about the volume of contribution) unless verbosely described.
