### ISSUE TITLE
Old versions of the daemon are stopped by an incompatible killall command

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#336]
Per @akavel in #307, killall is not a command in Windows, so the call to killall ipfs via the subprocess module in replay.py will not work on Windows (sans Cygwin).

This is less critical, as a means was introduced in IPFS v0.4.10 to allow the ipfsapi to shutdown the daemon. This is already implemented and in-place but the fall-through if this does not work is to killall, so it might be invoked in some unanticipated circumstances.

I am unaware of a cross-platform single line solution to kill a process by name. To account for Windows, we may try `os.system('ipfs')` if `killall` is not available. If we had a list of all ipfs pids, we could also loop through `os.kill(pid, signal.SIGKILL)`.

**Comment by akavel** [comment]
That said, on Windows there's [`taskkill`](https://encrypted.google.com/search?q=taskkill) ;)

**Comment by machawk1** [comment]
Thanks for the pointer, @akavel. I'd like to look at the various options for killing the process on Windows to see what's the most reliable. Ideally we would only kill the associated daemon and not any others started by other tools, e.g., github.com/ipfs-shipyard/station packages its own daemon, so would also die with something akin to `killall('ipfs')`.
