### ISSUE TITLE
Integrating Reconstructive

### ISSUE THREAD

**Issue by ibnesayeed** [oduwsdl/ipwb#338]
Integrate [Reconstructive](https://github.com/oduwsdl/reconstructive) to streamline ServiceWorker-based rerouting.

This should fix #335 and #337.

**Comment by machawk1** [comment]
@ibnesayeed Can you give a summary of what reconstructive is providing that is not covered by the current service worker implementation?

**Comment by ibnesayeed** [comment]
Reconstructive is implemented like a module which does not register itself as a ServiceWorker, but imported in any custom SW script to provide features of rerouting, rewriting, and banner inclusion. It is written in a way that allows overrides for for greater customization while utilizing the generic logic.

**Comment by ibnesayeed** [comment]
I did not change how SW is being registered, but made changes only to impact exclusions and the rerouting logic. I have imported the script directly from the reconstructive repo rather than packaging locally to allow any changes in the upstream to reflect immediately. Once it becomes stable enough, we can ship a copy of the script in this package.

**Comment by machawk1** [comment]
@ibnesayeed I have to perform offline tests while testing that PR, which is problematic when there's code that's pulled in from a remote location. Please make it self-contained within your branch.

Either that or get your reconstructive code to your liking, inclusive of the features implemented in the current SW, and submit the PR.

**Comment by ibnesayeed** [comment]
While adding the file locally is not an issue, in this early stage, it would be difficult keep files in sync in both the places. That's why I preferred the remote file for now. However, if you do perform some offline tests, it would be necessary to keep a copy locally. Do you think, the following approach would do the trick for now?

```js
try {
  importScripts('https://oduwsdl.github.io/reconstructive/reconstructive.js')
} catch (e) {
  console.log('Remote script loading failed, fallback to the local copy which may be stale', e)
  importScripts('reconstructive.js')
}
```

**Comment by machawk1** [comment]
@ibnesayeed There's a possibility that this could cause two different scripts to be tested based on the former's accessibility.

Why not just work in a branch in this repo then copy it over to the reconstructive repo once complete?

**Comment by ibnesayeed** [comment]
I will take care of it once some known issues are resolved.

**Comment by ibnesayeed** [comment]
This is ready for initial testing. Any rerouting issues should be reported in the other repo.

**Comment by machawk1** [comment]
Reconstructive should be fully integrated now thanks to @ibnesayeed.
