### ISSUE TITLE
Remove duplicate endpoints with similar logic

### ISSUE THREAD

**Issue by ibnesayeed** [oduwsdl/ipwb#342]
Currently, `replay.py` has two methods `showMemento` and `showMementoAtDatetime` that are being served at `/memento/<datetime>/<urir>` not at `/<datetime>/<urir>` respectively. The latter has duplicate behavior with less functionalities. I think the later should be removed completely, but before that we can set a redirect from one to the other to make sure other things are not breaking. More discussion on this can be found in #339. Current SW implementation actually performs this rerouting on the client side anyway, but for Reconstructive (#338) to be used efficiently, we need to remove this duplicate behavior.

**Comment by machawk1** [comment]
@ibnesayeed Can #339 go forward without this change?

**Comment by ibnesayeed** [comment]
I am yet to see what was the webui.js related issue that was caused due to a little change in the replay.py, so it is difficult to comment on that. If we really want to make it work, perhaps a lot of custom logic can be added in the service worker to make it work, but:

* that is not guaranteed to work
* it will be an even bigger pain to work with and maintain
* fixing the remaining issues in the reconstructive to deal with situations it is failing in right now would be difficult, and
* this endpoint should go away nonetheless

So, I don't really see a good reason to invest in causing more mess rather than taking the opportunity to clean up the code.

**Comment by ibnesayeed** [comment]
I looked at the code and workflow further and realized that in the current implementation `/<datetime>/<urir>` endpoint is only intended to be used by the navigational requests. For everything else (embedded resources that are not under special endpoints) the browser might think they are coming from `/<datetime>/<urir>`, but they are actually being served from `/memento/<datetime>/<urir>` using a plain rerouting logic:

https://github.com/oduwsdl/ipwb/blob/8d7f59e21060cab27cc8dcf79dbcf802ef19259e/ipwb/serviceWorker.js#L72-L74

So, the behavior for now is, if the navigational page (main/root memento page) at that datetime is not available then it will return a 404, but every other resource is almost guaranteed to have silently redirected to the closest memento while completely masking this act from the client/user. This is a very naive and confusing implementation which does not add any real value.

In the new Reconstructive implementation if we add an exclusion for navigational fetches and deal with them differently, then we will either end up duplicating the whole logic for this new pattern or will lose the opportunity to extract datetime from the referrer. Also, such exclusion would mean that we wont be able to leverage reconstructive features for adding banners or performing other rewriting tricks such as to make hyperlinks work as expected.

PR #343 is the simplest fix for now which is not expected to break anything. However, in future we might remove this endpoint completely.

**Comment by ibnesayeed** [comment]
With #450 fixed, I think it is tire to remove the unnecessary route.

https://github.com/oduwsdl/ipwb/blob/6b8ac9dd6b38128d7fa0db96f0b4a51bbde2a09a/ipwb/replay.py#L512-L516

**Comment by machawk1** [comment]
Ok, go ahead and submit a PR removing this function and route, @ibnesayeed.
