### ISSUE TITLE
Preserve mementos' original URI in CDXJ

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#347]
When generating the CDXJ in the indexer (note: NOT the CDXJ TimeMap), the URI-R of each memento is lost in the SURTing procedure. In #346 @ibnesayeed suggested we retain the scheme as a JSON attribute. Knowing the scheme of the URI-Ms will allow us to more accurately infer the scheme of the URI-R that is represented in TimeMaps, e.g., if all are http/https, the original can be populated with this respective scheme.

**Comment by ibnesayeed** [comment]
Preserving the original URL in the index will not only allow us to attach original scheme, but also any subdomain such as `www` that might have been stripped off in the SURT process.

**Comment by machawk1** [comment]
I agree. Ticket scope changed.

**Comment by machawk1** [comment]
Added in 66bddceb1ebdbe6ff022e61af15b54f08ca8150a
