### ISSUE TITLE
Supplied sample warc.gz file is not compressed properly

### ISSUE THREAD

**Issue by ibnesayeed** [oduwsdl/ipwb#350]
It looks like that the `ipwb/samples/warcs/salam-home.warc.gz` was compressed using usual `gzip` command rather that multi-block compression that is required for WARC files.

**Comment by machawk1** [comment]
From the WARC's contents, it was generated with, `wget --warc-file=salam-home-2 http://www.cs.odu.edu/~salam/`. using wget 1.16.1. We may want to re-generate it to see if wget is perhaps not generating WARCs using multi-block compression.

**Comment by ibnesayeed** [comment]
I was trying to index it without redirecting the output to a file when I saw an error complaining about the same.
