### ISSUE TITLE
Issue running docker image based on README

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#352]
When I run `docker container run -it --rm -p 5000:5000 oduwsdl/ipwb`, should the container/image/docker-entity-thing be pulled from dockerhub, some remote location, or from the local repo? When I run the above command from an empty directory with `Docker version 17.09.1-ce, build 19e2cf6` installed and the Docker daemon running, I get the error:
```
Unable to find image 'oduwsdl/ipwb:latest' locally
docker: Error response from daemon: pull access denied for oduwsdl/ipwb, repository does not exist or may require 'docker login'.
See 'docker run --help'.
```

/cc @ibnesayeed

**Comment by ibnesayeed** [comment]
That command will work once we set up an automated build on DockerHub. I did not set that up yet because updated Dockerfile  was not in the master branch before being merged.

**Comment by ibnesayeed** [comment]
This should work now.

**Comment by machawk1** [comment]
Confirmed as fixed.
