### ISSUE TITLE
We need to periodically tag releases

### ISSUE THREAD

**Issue by ibnesayeed** [oduwsdl/ipwb#353]
While we are following a rolling release style model currently, we should tag the repo with a version number after certain big changes.

**Comment by ibnesayeed** [comment]
This will be helpful to release tagged images on DockerHub rather than just the `latest` one based on the bleeding edge master.

**Comment by ibnesayeed** [comment]
Perhaps we can tag the repo every time we bump the version for PyPi.

**Comment by machawk1** [comment]
Often I will fix a bug that warrants a new version but isn't significant enough to be a "big change". Given how rapidly the code is evolving, I think it's redundant to have to add a tag for each tweak. We want the user on the bleeding edge master.

**Comment by machawk1** [comment]
I have been bumping the version number with each bug fix, so that would be a new tag for every single bug fix.

**Comment by ibnesayeed** [comment]
Well, it does to hurt to tag very often, though you can decide to tag the repo only when you bump the second point version number, not necessarily every third point bugfix bump.

**Comment by machawk1** [comment]
The current versioning is date-based, e.g., v. 0.2017.12.23.1741.

**Comment by ibnesayeed** [comment]
Whatever is the release strategy, I think it would be good to have a periodic tagged release when we feel that enough has been changed since the last release. Alternatively, we can tag the repo on every version bump, but remove last insignificant version tags to reduce the number of tags. This will ensure that a historical record of each release is available under the Releases tab automatically and each version also available in DockerHub's repo.

**Comment by machawk1** [comment]
That seems like a lot of bookkeeping. Is there any way to automate this with, say, having a script that calls the command to publish to pypi and create a new GitHub tag?

**Comment by machawk1** [comment]
There's [this script](https://gist.github.com/bclinkinbeard/1331790) that we could adapt. It might also be good to automate updating the version in `__init__.py` as part of this process.

**Comment by machawk1** [comment]
Ping @ibnesayeed, I have created a script to automate the tag creation and pypi deployment process. Let me know your thoughts and whether we could tie-in a hook to docker hub.

**Comment by ibnesayeed** [comment]
I can configure DockerHub to build on each tag creation.

**Comment by machawk1** [comment]
Can this ticket be closed with the introduction of deploy.sh and a few sample runs that populated the repo's tags/releases?

**Comment by ibnesayeed** [comment]
Sorry, I was busy elsewhere. Now it should be all set. There will be an automated build on each commit to the master branch which will have the docker image tag as `master` and two builds on each repo tag, one with the same tag as the repo tag and the other one as `latest`.

**Comment by machawk1** [comment]
@ibnesayeed No problem, I just wanted to get your confirmation that the requirements of this issue were met.
