### ISSUE TITLE
Release script does not update the code source in GitHub

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#358]
I noticed an issue when running the release.sh script. The tag/release is created in GitHub but the code source file containing the updated version number, `__init__.py` is not updated according to GitHub. It _does_ get updated in my local working directory when `release.sh` is run but for some reason the change to `__init__.py` does not get pushed to GitHub.

I thought that it was possibly `git push origin $TAG_NAME` that is used and required to push the newly created tag (and thus a new "version" in GitHub, required for the Docker hook) but removing that command in the script to simply be `git push origin` does not push the programmatically created tag.

Any advice on resolving this issue, @ibnesayeed?

**Comment by ibnesayeed** [comment]
I am not sure why it would not push changes to origin. However, `git push origin` is certainly not going to push that tag to origin. This command would push the current branch to the corresponding remote branch instead. I do see `__init__.py` being updated here, so I am not really sure what is the issue.

**Comment by machawk1** [comment]
I think it might just be lag in the GitHub web interface, as the update that was not present after the push is now there after some time has passed. I'll keep an eye out for it next time it's run. Thanks for the sanity check!
