### ISSUE TITLE
Rewrite the default and optional argument functionality for replay, indexing, and help

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#39]
Per @ibnesayeed in #37, reassign the default functionality as follows:
* `ipwb` returns the ipwb help docs of the CLI, also available via `ipwb help`
* `ipwb index` returns the help docs (params) needed to index a (W)ARC, also available via `ipwb index help`
* `ipwb index (warcPath)` returns a CDXJ. 
* `ipwb replay` starts the replay system
* `ipwb replay help` provides help docs/params for replay

**Comment by machawk1** [comment]
argparse really does not like to allow positional arguments like the above. A workaround would be to check if the command (index, replay, etc) is in a list, append '--' to make an optional argument, then go forward based with the condition of an optional # of values for the command (e.g., path for index), but the auto-generated help from argparse, one of its main appeals, would not express what we want from the user. Instead, it would reference the optional argument format ('--index'). 

There is definitely some elegance to 'ipwb replay', as I have seen executed in projects built in other languages (e.g., MemGator in Go). I will need to look how this is intuitively accomplished in Python without generating too much argparsing spaghetti.

**Comment by ibnesayeed** [comment]
There is something called `sub-command` that should be used for this behavior and it is supported by [argparse](https://docs.python.org/3/library/argparse.html#sub-commands).
