### ISSUE TITLE
Some responses do not have a newline at the end

### ISSUE THREAD

**Issue by ibnesayeed** [oduwsdl/ipwb#395]
TimeMaps do not return trailing newline.

```
$ curl -i http://localhost:5000/timemap/link/memento.us/
$ curl -i http://localhost:5000/timemap/cdxj/memento.us/
```

Following links from a TimeGate with an `Accept-Datetime` header includes a trailing newline, but without that header the response does not include a newline.

```
$ curl -iL -H "Accept-Datetime: Sat, 02 Feb 2013 10:00:00 GMT" http://localhost:5000/timegate/memento.us/
$ curl -iL http://localhost:5000/timegate/memento.us/
```

According to the POSIX standard, having a trailing newline character is necessary for text files. Not including that may cause some unexpected consequences when files are combined. Read more about it in [this StackOverflow thread](https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline).

**Comment by machawk1** [comment]
Check out:
https://github.com/oduwsdl/ipwb/blob/master/ipwb/replay.py#L443
https://github.com/oduwsdl/ipwb/blob/master/ipwb/replay.py#L486

For some reason the line feed was explicitly removed. This might be a simple fix but do you know of any reason of why we would have excluded the final LF in the past, @ibnesayeed ?

**Comment by ibnesayeed** [comment]
You might have though, removing that was a good idea as you were implementing that. It is not something that was changed later, instead explicit removal of the last byte was part of the first commit that included TMs in these formats. Another possibility is that you might have tried taking some inspiration from the MemGator implementation, but misinterpreted something.

**Comment by machawk1** [comment]
@ibnesayeed I took a naive route and first decremented the list range but that included a superfluous comma that was previously removed from the join of the array elements. I then tried appending a CRLF but to `generateCDXJTimeMapFromCDXJLines()` and `generateLinkTimeMapFromCDXJLines()` but that surfaced up an error stating, "Detected newline in header value.  This is a potential security problem", which I think was part of the motivation behind the current logic.

This ought to be a simple fix but not as simple (and hacky) as I thought.

**Comment by ibnesayeed** [comment]
It looks like the `redirect()` function of Flask does not add a new line in the HTML payload, so the TG part will still remain the way it is unless we customize the response. However, I have fixed many newline and whitespace issues in both TM formats as well as Link header in #401.
