### ISSUE TITLE
Convert the README.rst to .md to prettify the dockerhub display

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#399]
https://hub.docker.com/r/oduwsdl/ipwb/

...shows the symbols used for linking and formatting in https://github.com/oduwsdl/ipwb/blob/master/README.rst. RST was originally used for display in pypi. Pypi has since had a UI overhaul. Is the markdown support any better? If so, we might try to move to MD for the sake of readability in dockerhub. Alternatively, we might look to finding a way to ensure the README does not contain the meta content and still use the README.rst.

**Comment by ibnesayeed** [comment]
Looks like the proposal to support Markdown in PyPi is finally implemented.

https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi

**Comment by machawk1** [comment]
@ibnesayeed The README has been updated to MD and displays fine in GitHub and PyPi. Dockerhub seems to choke, however. Can you figure out what, if anything, Dockerhub requires differently than GitHub and PyPi in its MD?

**Comment by machawk1** [comment]
Does an interface exist where I can test how MD will be rendered on Dockerhub?

Go ahead and try to fix them if you can without changing the visual display of the GitHub/PyPi document. If that's not possible (i.e., DockerHub MD restriction prevents some GH-MD feature), let me know.

**Comment by ibnesayeed** [comment]
No, I don't think they have a preview option, but I am sure I can fix it. I will work on this and push changes to the `issues-399` branch. If those changes don't work well, then we can revert them.

**Comment by machawk1** [comment]
@ibnesayeed I recall you mentioning display issues with the README on DockerHub within some other repo. Can you link it here? The line breaking on the DockerHub version of the ipwb README contains odd line breaking, mis-aligned consecutive code blocks, etc.

**Comment by ibnesayeed** [comment]
Line breaking in the DH rendering is a long-known issue https://github.com/docker/hub-feedback/issues/124. If we want to fix that now and make it consistent across all three places, we can just remove all the newlines from the MD source where they are not needed.

I have reported the misaligned consecutive code lines issue https://github.com/docker/hub-feedback/issues/988#issuecomment-403898203.

**Comment by machawk1** [comment]
@ibnesayeed I was wondering what you meant by the first statement, checked out the README.md and noticed superfluous line breaks to a line width (maybe 80-chars?). This may have been the result of the RST->MD conversion script, as I am not prone to manually applying this sort of line breaking to free-form text (code is a different story).

**Comment by machawk1** [comment]
@ibnesayeed Do you think we can close this ticket or is more adjustment needed?

**Comment by ibnesayeed** [comment]
There is one little thing that I will fix and close this.

**Comment by machawk1** [comment]
Oh, right, is it the extra CRLF?

**Comment by ibnesayeed** [comment]
> Oh, right, is it the extra CRLF?

Yes!

This should be sorted out by the #438 PR.
