### ISSUE TITLE
Update README for new argument system introduced in #39

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#40]
@ibnesayeed Please play with the new calling structure to see if it's intuitive and feel free to start updating the README to be representative.

**Comment by ibnesayeed** [comment]
I will take care of it.

**Comment by machawk1** [comment]
It's no longer "Hacktober", @ibnesayeed, removing the label. ;)

**Comment by ibnesayeed** [comment]
I am planning to give the new CLI a try this weekend.

**Comment by machawk1** [comment]
I took card of this, @ibnesayeed. ✅  Please give the new CLI a spin and see if the README is representative when you get the chance.
