### ISSUE TITLE
Misreported number of "HTML pages listed" in replay interface

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#405]
`ipwb index ipwb/samples/warcs/5mementos.us | ipwb replay`
shows the following interface at http://localhost:5000/.

<img width="1064" alt="screen shot 2018-06-28 at 6 40 02 pm" src="https://user-images.githubusercontent.com/2514780/42064070-c0ed0e18-7b02-11e8-80a0-1c499447a88f.png">

"3 HTML pages listed" is likely in reference to "3 unique URI-Rs". This verbiage ought to be corrected.

**Comment by machawk1** [comment]
Listing the URIs is not scalable but really useful, particularly to those that are using ipwb on a small data set. The URI-Rs ought to be coalesced with the available mementos at the various listed datetimes (above) remaining accessible.

**Comment by machawk1** [comment]
@ibnesayeed Suggestion on the UI for this?

**Comment by ibnesayeed** [comment]
One design that I think can make the landing page both useful and more realistic for both small and relatively bigger collections might be something as described below:

* Move administrative options off of the landing page as per #213
* Report a more detailed capture summary, something like, `<N> mementos of <M> resources with <K> HTML pages between <Date1> and <Date2>`
* List `<P>` most recently captured unique HTML pages with titles (as per #178) and human readable time (similar to the `moment.js` functionality)
* In future, if we have collection-wise organization, something about that can also be reported in the landing page

All of this information can be retrieved once when the server is started and stored in variables (in memory), making it super snappy to serve the landing page. These values only needs to be updated when the index is updated.
