### ISSUE TITLE
Empty display when 404 using text input on main replay

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#411]
Using the search box on the replay page for a URI with 0 mementos returns an empty viewport when using a browser.

Also returns a 200 when viewed with curl. This should probably be a 404, right @ibnesayeed?

Replicate:
1. `ipwb index ipwb/sples/warcs/5mementos.warc | ipwb replay`
1. Enter `example.com` in search box and submit form.

43d1637fbfdf1754e5576ab1f392d3fd346c1e94

**Comment by ibnesayeed** [comment]
> @machawk1: Also returns a 200 when viewed with curl. This should probably be a 404, right @ibnesayeed?

Yes!

**Comment by machawk1** [comment]
I think this is the product of consolidating redundant functions. Regardless, we can work on reverting this response to be a 404. When a user encounters a 404 on the ipwb replay system, what should they see from a browser?

**Comment by ibnesayeed** [comment]
> When a user encounters a 404 on the ipwb replay system, what should they see from a browser?

Perhaps a synthetic 404 page with proper message telling them about the situation and included pre-filled form with the search URI.

**Comment by machawk1** [comment]
Pre-filled with what?

**Comment by ibnesayeed** [comment]
> Pre-filled with what?

Say, the user searched for `example.com` and no mementos were found, then they should see a 404 page which has a clear message and a form somewhat similar to the landing page which has `example.com` pre-filled. The reason for this is to allow them to correct any typos they might have which caused the 404. However, this should not be the behavior if it was a captured 404.
