### ISSUE TITLE
Allow fuzzy/free text searches of the archives from the replay URI input box

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#417]
Per https://github.com/oduwsdl/ipwb/pull/416#pullrequestreview-134440243

@ibnesayeed suggested:
> accept queries in natural language like example.com 3 months ago

This would be a novel feature as a search method for an archival replay system.

**Comment by ibnesayeed** [comment]
I had a feeling that when I found out about Chrono last year, we discussed the possibility of using it in IPWB and MemGator. It turns out, we did create a ticket #111 at that time. So, this is essentially a duplicate.

**Comment by machawk1** [comment]
Closing as duplicate.
