### ISSUE TITLE
Replay ignores supplied index when the context is not a TTY

### ISSUE THREAD

**Issue by ibnesayeed** [oduwsdl/ipwb#426]
When running replay in a Docker container in detached (`-d`) mode, no TTY is associated, in which case the reply ignores the supplied index and creates an empty index to replicate the behavior as if the replay was receiving index from a pipe. As a side note, index from a pipe implementation is very rudimentary.

**Comment by machawk1** [comment]
@ibnesayeed and I had an extensive in-person discussion on resolving this issue.

The proposal involves revising the way `ipwb replay` is reading and processing its parameters. One issue is that if a user types simply `ipwb replay`, a default WARC is indexed and replayed.

Doing `ipwb index some.warc | ipwb replay` currently causes the replay script to read from the pipe as a source for the CDXJ to be replayed.

A common UNIX convention is to use the `-` parameter to read the piped output in receiving commands.

We will revise the index/replay systems to acts as follows:
* `ipwb replay` will cause the default WARC content to be indexed and replayed.
* `ipwb index some.warc | ipwb replay` will _also_ cause the default WARC content (_not_ some.warc) to be indexed and replayed.
* `ipwb index some.warc | ipwb replay -` will instruct the replay system to read the CDXJ result from the indexer from the pipe and replay it.
* `ipwb index some.warc | ipwb replay someOther.cdxj` will cause the replay system to ignore what is on the pipe and use `someOther.cdxj` as the basis for replay.
* `ipwb replay someOther.cdxj` will instruct the replay system to use `someOther.cdxj` as the basis for replay.

Much of this can be done in `__main__.py`.

**Comment by machawk1** [comment]
It will also be important to consider the behavior of using `-` as a parameter on Windows.

**Comment by ibnesayeed** [comment]
Yes, let's go for this interface for now to avoid the ambiguity due to the missing index.

**Comment by machawk1** [comment]
Docker usage to replicate locally prior to distribution to dockerhub:

```
docker image build -t oduwsdl/ipwb .
docker container run --rm -it -p 5000:5000 oduwsdl/ipwb ipwb replay
docker container run -d --name=sawood -p 5000:5000 oduwsdl/ipwb ipwb replay
```

In both of the last two commands, check the browser. The behavior should be the same.

To test a CDXJ file:

```
$ docker container run -it --rm -v /tmp/ipwbdata:/data oduwsdl/ipwb ipwb index -o /data/cdxj/custom.cdxj ipwb/samples/warcs/5mementos.warc
$ docker container run -it --rm -v /tmp/ipwbdata:/data -p 5000:5000 oduwsdl/ipwb ipwb replay /data/cdxj/custom.cdxj
```
This will not allow us to test `-` param or pipe tests. This will allow us to test the first and last scenarios of replay enumerated above.

**Comment by machawk1** [comment]
@ibnesayeed Any suggestions on how to see ipwb's output? `docker logs -f <containerid>` only shows messages from ipfs.

**Comment by ibnesayeed** [comment]
Did you rebuild the Docker image from the current `master` branch?

**Comment by machawk1** [comment]
@ibnesayeed Yes, I ran the commands in the [above comment](https://github.com/oduwsdl/ipwb/issues/426#issuecomment-403687480) to build from my working copy representative of the state of the `master` branch.

I can replicate that the index is not read in detached mode. However, I cannot see the ipwb log, just the ipfs output.

**Comment by machawk1** [comment]
@ibnesayeed Disregard the above. I can now see the ipwb output from the container.

**Comment by ibnesayeed** [comment]
Let's try for the following simple and intuitive behavior:

* `ipwb replay` should print replay help to highlight that a CDXJ file argument is mandatory
* `ipwb index some.warc | ipwb replay` should utilize the resulting index received from the pipe for replay
* `ipwb replay sample.cdxj` should use `sample.cdxj` for replay

Let's get rid of the magical default index file on replay that has to go through a bootstrapping process of populating IPFS without explicitly calling indexing. Quick getting started behavior can be documented instead of hardcoding in the main code. We can suggest people to run `ipwb index ipwb/samples/warcs/salam-home.warc | ipwb replay` for a quick test. Also, the default command in our Dockerfile can have a similar default behavior.

Use `os.isatty()` instead of `sys.stdin.isatty()` to check if a pipe is present for input.
