### ISSUE TITLE
test-requirements.txt files does not exist

### ISSUE THREAD

**Issue by ibnesayeed** [oduwsdl/ipwb#443]
The CI script should be updated to reflect this.

https://github.com/oduwsdl/ipwb/blob/f870b242e895379eabdb427ae5726e3e12eead51/.travis.yml#L11

**Comment by machawk1** [comment]
@ibnesayeed I need some clarification on this. There is a `test-requirements.txt` file in the root of the repo.

**Comment by ibnesayeed** [comment]
Oh, I was testing something from inside of a Docker container. It turns out that this file is not copied into the docker image due to a line in the dockerignore file.

https://github.com/oduwsdl/ipwb/blob/01830df4d68c9451f66dae4f59de57eade6866a6/.dockerignore#L10

**Comment by machawk1** [comment]
Sounds like a bug in the docker config. Please submit a PR or push directly.

**Comment by ibnesayeed** [comment]
I don't think we need tests or test requirements inside of the image that is intended for running the server. If we want run tests inside a container, we can bind-mount repo directory from  the host machine or clone inside.
