### ISSUE TITLE
Server should not be killed if one request has any issues

### ISSUE THREAD

**Issue by ibnesayeed** [oduwsdl/ipwb#444]
This `sys.exit()` call in the replay is dangerous. If it gets hit dues to a a request falling into an unrecognized exception, the whole replay server daemon will die. This should just log the exception, return `HTTP 500 Internal Server Error` and move on.

https://github.com/oduwsdl/ipwb/blob/f870b242e895379eabdb427ae5726e3e12eead51/ipwb/replay.py#L620

Other two uses of the `sys.exit()` in the same script are fine as they will only occur at the startup, not when the server is up and serving.

**Comment by machawk1** [comment]
500s scream of misconfiguration for some reason. This condition is a catch-all. I agree that exiting the script is the wrong response but a 5XX is really generic. Suggestions?

Can you imagine a test case that invokes this?

**Comment by ibnesayeed** [comment]
> I agree that exiting the script is the wrong response

Exiting the script is not a response, it would drop all current connections and the server will go down.

> but a 5XX is really generic.

> Since it is a safeguard catch-all type exception handling where all the known specific cases are individually handled with appropriate responses, `500` would be the most accurate one. Note that this response will be returned to only requests that hit the exception, not necessarily every other connected client.

> Can you imagine a test case that invokes this?

If we would know any specific exceptions that we are not handling already then will handle them instead. If you want to test it, you can raise a synthetic exception from the try block in your local code to see the effect, no need to commit that.

**Comment by machawk1** [comment]
> Exiting the script is not a response,

Not in the technical/HTTP sense, no, but something is happening because of another things...response. ;)

I agree that the server ought to keep running if this condition occurs instead of the script exiting.
