### ISSUE TITLE
Link on replay homepage omit /memento/ in path, always resulting in an initial redirect

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#450]
Links to mementos on replay page point to scheme://host/date/URIR instead of scheme://host/memento/date/URIR.

@ibnesayeed Can you think of a reason why we need to link to the URI-M without the `/memento/` part of the path?

**Comment by ibnesayeed** [comment]
Since I have discovered the two endpoints I have always been against this redundancy (#342) which now simply redirects global one to the namespaced one (#343). Once we remove these generated global links from the landing page, we can actually remove that endpoint from the replay.
