### ISSUE TITLE
Why is this exact test function name test_mementoRelations_one defined twice?

### ISSUE THREAD

**Issue by ibnesayeed** [oduwsdl/ipwb#470]
Is this by mistake or intentional?

https://github.com/oduwsdl/ipwb/blob/c2895694c0b17df3e8179e2fe7d64d180d62b0d4/tests/test_memento.py#L79-L85

**Comment by machawk1** [comment]
Top one was a placeholder but was since implemented by the bottom one. The top one can be removed.
