### ISSUE TITLE
If IPFS daemon is not running, sample CDXJ still used

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#487]
InterPlanetary Wayback 0.2018.08.09.0340

```
ipwb index ipwb/samples/warcs/5mementos.warc | ipwb replay
Daemon is not running at http://localhost:5001
Daemon is not running at http://localhost:5001
Sample data not pulled from IPFS.
Check that the IPFS daemon is running.
getting index file at //tmp/446R87.cdxj
IPWB replay started on http://localhost:5000
```
<img width="1087" alt="screen shot 2018-08-09 at 1 22 53 pm" src="https://user-images.githubusercontent.com/2514780/43914976-5beaa5ac-9bd7-11e8-9a57-25eb060ae7e5.png">

**Comment by ibnesayeed** [comment]
A few things to note here:

* I don't know what `Sample data not pulled from IPFS.` message means. We do not pull any sample data from IPFS.
* We might want to seed our random sample generator for the temporary CDXJ file as it might generate the same filename more often if the state of the random number generator is the same each time the script starts.
* Are we storing the state of the INDEX_FILE in the config? That might be something that persists the previous index.

**Comment by machawk1** [comment]
Regarding point 3, we were but I don't think we still are. I nuked the `Ipwb` object in the IPFS config (you have another ticket (#?) of IPWB having its own config), reinstalled, and re-ran. The sample data was still used but the new sample index was _not_ written to the config like occurred prior to our changes yesterday.

Point 1: Before, we were using the sample WARC to push the contents into IPFS then **PULLING THE SAME DATA FROM IPFS**. That's the significance of this message. Going from WARC->IPFS->CDXJ then from CDXJ->IPFS->HTTP on replay ensured that we were not relying on the same data to continually be pinned by another user on user 1's first-launch.

**Comment by machawk1** [comment]
This scenario requires the interaction of the indexer and the replay system to reproduce. Running the indexer alone reports that the daemon is not running and quits. The code is reading that piping is occurring, trying to unsuccessfully read the pipe from the replay system, and defaulting to the sample data when no "index" is readable as a source for replay.
