### ISSUE TITLE
First and last links in reconstructive banner do not use proxy

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#503]
![screen shot 2018-08-14 at 6 30 35 pm](https://user-images.githubusercontent.com/2514780/44122192-c1c9e302-9ff0-11e8-87f9-b2fe81bb0008.png)

Shown is hovering over "last" link in the banner, which refers to a memento at port 5000 when the replay system is running at 5002.

This is likely related to the issue in #327 of the TimeGate endpoint not yet being looped into the proxy mode.

**Comment by machawk1** [comment]
Encountered on 4ef1c420c402489ad201262d55258ee1c66780bb, the current head of the issue-436 branch but likely replicable on master (needs verification).

**Comment by ibnesayeed** [comment]
I don't see this behavior on our pilot deployment. Are you sure you are setting the proxy flag when running the server?

**Comment by machawk1** [comment]
@ibnesayeed I am not. I am running it in docker with 5002 mapped to 5000.

**Comment by ibnesayeed** [comment]
yeah, your internal process is unaware of that port mapping, so this has to happen. This is precisely why we have the proxy configuration. When running the replay, specify the flag as follows:

```
$ ipwb replay --proxy="http://localhost:5000" /path/to/index.cdxj
```

Even if you are piping index file, do supply this config in the replay:

```
$ ipwb index /path/to/sample.warc | ipwb replay --proxy="http://localhost:5000"
```

**Comment by machawk1** [comment]
That fixed the issue. Thanks, @ibnesayeed.

Perhaps we should document an example like this using Docker+proxy mode.

**Comment by ibnesayeed** [comment]
> Perhaps we should document an example like this using Docker+proxy mode.

Yes, we should!
