### ISSUE TITLE
Routing the CDXJ to another file using > prevents the prompt msg for a key from displaying in encryption mode

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#52]
It also makes it appear that the indexer is hanging. Maybe use another comm channel than the default used by prompt.

**Comment by machawk1** [comment]
Replicate from the root of the repo:
```sh
ipwb index -e ipwb/samples/warcs/salam-home.warc > output.cdxj
```

The CLI will take whatever is entered as the key but then the prompt "Enter a key for encryption:" is put in the redirected output!

**Comment by ibnesayeed** [comment]
@machawk1, did you also test it with the `-o` flag?

**Comment by machawk1** [comment]
@ibnesayeed I did not. This ticket predates that flag. Regardless, it ought to be tested.

**Comment by machawk1** [comment]
@ibnesayeed: `$ ipwb index -e ipwb/samples/warcs/5mementos.warc -o ./sawood.cdxj` 
asks for the key with a prompt as expected and the prompt does not get propagated to the output file (the crux of this ticket).

**Comment by ibnesayeed** [comment]
There should be a way to supply encryption key inline or from a file, because prompts are not the best way when some scripted automation is to be done.

**Comment by machawk1** [comment]
@ibnesayeed I completely agree. The encryption aspects did not making the initial release and the functionality has slowly been added. I think it would be worthwhile to consider the encryption dynamics more including the methods you supplied for users to supply the key.

**Comment by machawk1** [comment]
Also relevant: #242
