### ISSUE TITLE
Remove README info about running from source without installation

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#53]
I believe having this information in the README causing the instructions for getting up and running to be more convoluted, particularly with suggesting to use a virtual environment and all of the baggage that implicitly comes with this. Let's move over to just describing the installation via pip and running using the installed `ipwb` binary. I think this follows the trends of other projects that are registered with pypi. @ibnesayeed ?

**Comment by ibnesayeed** [comment]
One way to keep that in the README in a useful manner would be to have a separate heading as build instructions. That way contributors of the code know how to test their fresh changes before submitting a PR. This will be equally useful for those who want to run the tool based on the master (or some other) branch or a specific commit.

**Comment by machawk1** [comment]
@ibnesayeed If they want to install via the master branch, they can still install using pip. The purpose of this ticket is to remove the additional instructions of running the code using (e.g.) `python ipwb/indexer.py (warcLoc)` and instead require pip install (pip install ./ from src) then running via `ipwb indexer (warcLoc)`.

**Comment by ibnesayeed** [comment]
That's what I said, running from the source is not for users, but for developers. so we can move those instructions under a separate heading to tell other developers how to run the raw code while making changes in the code and when satisfied, how to build binary from it.

**Comment by machawk1** [comment]
@ibnesayeed I agree.
