### ISSUE TITLE
Submitting an empty query string on the main replay textbox displays an error

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#530]
Replication:
* `docker image build --build-arg SKIPTEST=true -t oduwsdl/ipwb:2 .` of 4f28a50bb6fd12df22f83e86ccee38cbea9763e4
* `docker container run -it --rm -p 5002:5000 -v "$PWD":/ipwb oduwsdl/ipwb:2 bash`
* `ipfs daemon &`
* `ipwb index ipwb/samples/warcs/5mementos.warc | ipwb replay --proxy=localhost:5002`
* Access localhost:5002 in a browser
* Hit Search URL in the archive button
* Note "Error" displayed in viewport

Console says:
```
cannot concatenate 'str' and 'NoneType' objects
(<type 'exceptions.TypeError'>, TypeError("cannot concatenate 'str' and 'NoneType' objects",), <traceback object at 0x7fade02cc5a8>)
```

We have seen this error before. Let's write a test to check for this in the future in addition to handling the case of an empty query string.

**Comment by ibnesayeed** [comment]
I can take care of this!

**Comment by ibnesayeed** [comment]
So, this situation arises when a lookup is performed without a URI-R. This should ideally be a case of `400` response code. However, we would perhaps want the user to be redirected to the landing page. We might also place some JS restriction to prevent it from happening, but I am not quite sure what the final experience should be.

**Comment by machawk1** [comment]
@ibnesayeed The experience you described would be better than the current result. Implement at least the portion to give more guidance to the user (prevent the viewport from just showing "Error") and it would be a great improvement.
