### ISSUE TITLE
Title extraction when indexing a page has no title produces error

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#532]
```
ipwb index ipwb/samples/warcs/5mementos.warc | ipwb replay --proxy=localhost:5002
Failed to extract title in 5mementos.warc: 0/7
'NoneType' object has no attribute 'text'
...
```
There ought to be a check in the indexer that `title = BeautifulSoup(payload, 'html.parser').title` is not `None` before accessing the `title = BeautifulSoup(payload, 'html.parser').title.text` attribute.

**Comment by ibnesayeed** [comment]
I thought about that, but I realized it's not necessary as the title won't be extracted if missing. So, I just wrapped the whole thing in a single try block. Hence I won't call it a bug. However, if the obvious exception there is too annoying, we can add more conditional statements.

**Comment by machawk1** [comment]
If an exception is thrown because you are trying to access an attribute of a variable/object/whatever that is `None`, that is a bug. ;)

**Comment by ibnesayeed** [comment]
Now that we have more code to deal with it, the argument is over. However, that `None` possibility was already wrapped in a try block and was not breaking the application execution. The scary message that was logged was a handled exception not a slipped one. With this new code, there is no change functionally or operationally, except, now we have no logs when HTML pages have missing title element, earlier we did.

**Comment by machawk1** [comment]
`Failed to extract title in 5mementos.warc: 0/7`
^ This is good.

`'NoneType' object has no attribute 'text'`
^ This is not.

Let's get the _good_ message back in the logs, as it is useful (albeit verbose).

**Comment by machawk1** [comment]
Looking at the code, the `catch` is generic. How about we mention in the initial conditional that `no title existed/found` not that the `extraction failed`?

**Comment by machawk1** [comment]
Additionally, though it is recommended that `Content-Type` be specified, it is not mandatory. We are applying the extraction procedure on this HTTP header being present in the WARC record and `text/html`. I will create a WARC where this fails using this assumption. If nothing else, the WARC may be useful down the line.

**Comment by ibnesayeed** [comment]
> Looking at the code, the catch is generic. How about we mention in the initial conditional that no title existed/found not that the extraction failed?

We can add more informative log entries, there is no harm in doing that. However, so far we are not providing any context about which resource the title extraction failed.

**Comment by ibnesayeed** [comment]
> Additionally, though it is recommended that Content-Type be specified, it is not mandatory. We are applying the extraction procedure on this HTTP header being present in the WARC record and text/html.

Title is not a mandatory, but opportunistic feature, hence missing a few false negatives is not critical. Hunting for title in a resource that doers not provide content-type is more work than necessary because many of those resources might not be HTML in the first place.

We can extract the title extraction login in a function once we start using warcio. We will pass the whole WARC object and return a suitable title (which might also include title for non-HTML resources). Currently, we are checking for some pre-conditions to identify the potential subset of resources that might have titles.

**Comment by machawk1** [comment]
Also note that we use a similar basis of checking content type on the main replay page to identify HTML pages of the set of mementos available. This causes the URI-M in the above WARC to not be identified as an HTML page and thus the replay UI reports that 0 HTML pages are available by default.

**Comment by ibnesayeed** [comment]
> Also note that we use a similar basis of checking content type on the main replay page to identify HTML pages of the set of mementos available. This causes the URI-M in the above WARC to not be identified as an HTML page and thus the replay UI reports that 0 HTML pages are available by default.

Which is fine, as there is only how much we can do if the page was initially silent about it.

[RFC2616](https://tools.ietf.org/html/rfc2616#section-7.2.1)

```
   Any HTTP/1.1 message containing an entity-body SHOULD include a
   Content-Type header field defining the media type of that body. If
   and only if the media type is not given by a Content-Type field, the
   recipient MAY attempt to guess the media type via inspection of its
   content and/or the name extension(s) of the URI used to identify the
   resource. If the media type remains unknown, the recipient SHOULD
   treat it as type "application/octet-stream".
```
