### ISSUE TITLE
New dead code in JS

### ISSUE THREAD

**Issue by ibnesayeed** [oduwsdl/ipwb#562]
After new changes in the resource listing logic, following code is now useless (it is executed and not unreachable though).

https://github.com/oduwsdl/ipwb/blob/f0f7fdbee058b909ea39b8c44fc1af3252e92546/ipwb/assets/webui.js#L20

With that in effect, `shortestFirst` function is also useless now.

**Comment by machawk1** [comment]
I would not say that it is _useless_ but rather, unused. The gist of the logic ought to be brought back into the current display mechanism.

**Comment by machawk1** [comment]
`Object.entries` enumeration is not guaranteed to be sorted. Maybe we ought to do the sort on the client side just prior to displaying the entries...perhaps sort the `li`s by respective `innerHTML.length`.

**Comment by ibnesayeed** [comment]
I think `Object.entries` respects the insertion order.

**Comment by machawk1** [comment]
@ibnesayeed I think it does but it's not guaranteed per a cursory scan of cautious coders on the web. Let's go a more guaranteed sorting route.

**Comment by ibnesayeed** [comment]
https://github.com/oduwsdl/ipwb/blob/f0f7fdbee058b909ea39b8c44fc1af3252e92546/ipwb/assets/webui.js#L23-L24

Change these lines to:

```js
  uriKeys.forEach(urir => {
  uris[urir].forEach(function (memento) {
```

This should restore the previous sorting behavior.
