### ISSUE TITLE
Link to IPFS WebUI is broken

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#567]
In 00c811a/v0.2018.09.19.1858, it points to http://127.0.0.1:5001/ipwbassets

**Comment by machawk1** [comment]
Thinking about it a bit more, even if the URI to the IPFS webUI was "correct", it would not be accessible using Docker unless the port was mapped. Perhaps there ought to be a check for this and tweak the UI accordingly.

**Comment by ibnesayeed** [comment]
Yes, we are not exposing that in out Docker deployment yet because that might allow others to abuse our test system. Other than that, it is not difficult to expose that, but I would perhaps wait until we decouple IPFS from IPWB. That does not mean we should not fix it here though.

**Comment by machawk1** [comment]
> That does not mean we should not fix it here though.

Right, and however we are deploying it in the test system we can prevent HTTP access to the daemon by not mapping the port in the docker invocation, correct?

It is odd that is it resolving to _just_ ipwbassets and nothing more.

**Comment by ibnesayeed** [comment]
> Right, and however we are deploying it in the test system we can prevent HTTP access to the daemon by not mapping the port in the docker invocation, correct?

Yes, by not exposing and mapping the daemon port, we are keeping it inaccessible from outside of the container.
