### ISSUE TITLE
When ipfs daemon is not running and indexer output is redirected, the error is shown in the resultant cdxj instead of displayed on the ipwb command-line

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#58]
For example, if I run:
```sh
ipwb index myArchive.warc > myArchiveIndex.cdxj
```
and the IPFS daemon is not running, `myArchiveIndex.cdxj` will contain the string `Daemon is not running at http://127.0.0.1:5001` and nothing else whereas ipwb should have thrown an error instead of outputting a file.

**Comment by jbenet** [comment]
please let us know how we can make the `ipfs daemon` UX better for tools like ipwb

**Comment by machawk1** [comment]
@jbenet Will do. The move from the previously named Python modules ipfs-api/ipfsApi to the ipfsapi module has caused some particular confusion, even if installed ipwb from pip, if the version of the module is not explicitly defined. Otherwise it seems to work well. I will be continuing to poke at the `ipfs daemon` as ipwb evolves.

**Comment by machawk1** [comment]
This issue still exists but might just being a matter of ensuring the `print` statement associated with  the inability to connect to the daemon is using stderr.
