### ISSUE TITLE
Long titles cause wrapping, use text-overflow?

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#596]
When a title on Web page is extracted and found to be very long, the ipwb replay interface will display the entire title.

![screen shot 2018-11-01 at 3 56 02 pm](https://user-images.githubusercontent.com/2514780/47876129-dfb5f900-ddee-11e8-91f4-99fd565c7173.png)

Should ipwb limit the title to a single line for readability/aesthetics?

While #543 has this information being moved to the admin page, the visual effect will remain if the current display logic is reused.

WARC to replicate the above screenshot attached.

[3mementos_longTitles.warc.txt](https://github.com/oduwsdl/ipwb/files/2539882/3mementos_longTitles.warc.txt)

**Comment by ibnesayeed** [comment]
We can use ellipsis in CSS for this, but perhaps we would also like to add `title` tag to those links so that full titles can be seen in tooltip.

```
text-overflow: ellipsis;
overflow: hidden;
white-space: nowrap;
```

**Comment by machawk1** [comment]
@ibnesayeed The approach you described would work well to resolve this issue.
