### ISSUE TITLE
Update to Flask ≥ 1.0

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#616]
ipwb currently uses Flask version 0.12.4. #613 was an attempt by a bot to update the repo with a newer version to solve a (still present) security issue. This caused ipwb tests to fail due to some difference between 0.12.3 (at the time) and 1.0.

This ticket represents an effort to move to a newer version of Flask.

**Comment by machawk1** [comment]
Within `show_uri()` in replay.py, the usage of signal (using Flask 1.0) produces the error `signal only works in main thread`. This is not shown in Flask < 1.0. We discussed this in #310. `signal` is used for a sort-of timeout functionality due to the timeout associated with the `.cat()` function in ipfsapi not working as expected at the time of implementation in ipwb.

**Comment by machawk1** [comment]
Flask 1.0 might be having issues processing the `Accept-Datetime` header in `test_acceptdatetime_status()`. The below is exhibited with the non-compliant datetime (Thu, 31 May 2007 20:35:00, note lack of TZ) whereas the first test of this function (Thu, 31 May 2007 20:35:00 GMT, compliant datetime) passes as expected with a 302. The second test is returned an HTTP 500 when a 400 is expected in the test parameters.

```
400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
(<class 'werkzeug.exceptions.BadRequest'>, <BadRequest '400: Bad Request'>, <traceback object at 0x7f1aab8b7c08>)```

**Comment by machawk1** [comment]
Within `queryTimeGate()` of replay.py, the code:

```
if not ipwbUtils.isRFC1123Compliant(adt):
        abort(400)
```

is properly reached and executed. A 400 is returned per the test:

```
400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
```

yet the test fails:
```
warc = '5mementos.warc', lookup = 'timegate/memento.us'
acceptdatetime = 'Thu, 31 May 2007 20:35:00', status = 400

    @pytest.mark.parametrize("warc,lookup,acceptdatetime,status", [
        ('5mementos.warc', 'timegate/memento.us',
         'Thu, 31 May 2007 20:35:00 GMT', 302),
        ('5mementos.warc', 'timegate/memento.us',
         'Thu, 31 May 2007 20:35:00', 400),
        ('5mementos.warc', 'timegate/memento.us',
         'Thu, 31 May 2007 20:35 GMT', 400),
        ('5mementos.warc', 'timegate/memento.us',
         '20181001123636', 400)
    ])
    def test_acceptdatetime_status(warc, lookup, acceptdatetime, status):
        ipwbTest.startReplay(warc)

        headers = {'Accept-Datetime': acceptdatetime}

        resp = requests.get('http://localhost:5000/{}'.format(lookup),
                            allow_redirects=False, headers=headers)
>       assert resp.status_code == status
E       assert 500 == 400
E        +  where 500 = <Response [500]>.status_code
```
Why is this 500 and not 400, as returned from the code?

**Comment by machawk1** [comment]
`abort(400)` seems to be the culprit here. If I replace it with `return "Bad Request", 400`, the tests pass in Flask 1.0.

**Comment by machawk1** [comment]
Changing the remaining `abort()`s to return "Msg", STATUS_CODE still causes the same tests to fail as the previous message.

**Comment by machawk1** [comment]
In `showMemento()` within replay, we set the Link header with `resp.headers['Link'] = linkHeader`. `resp` is a tuple:

```
'tuple' object has no attribute 'headers'
(<class 'AttributeError'>, AttributeError("'tuple' object has no attribute 'headers'"), <traceback object at 0x7efeb1ec5f08>)
```
Perhaps it was an object in Flask < 1.0. This needs be changed for the above memento tests to pass but the position of headers is unreliable in the tuple (it can be the first or second item).

**Comment by ibnesayeed** [comment]
`resp` can be initialized from various places in that execution chain depending on certain conditions. You might want to follow the execution path in debug mode. Also, it might be helpful to print the state of the `resp` in different places as you step through.
