### ISSUE TITLE
Test functionality in Python 3.8 (released Oct. 18, 2019)

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#624]
With a new version of Python released, this might be a good opportunity to write some tests or at least considering doing so.

* homebrew on macOS [still only installs 3.7.6](https://github.com/Homebrew/homebrew-core/blob/master/Formula/python.rb). A manual install procedure or using Docker might initially suffice for testing.

_this issue is intentionally open-ended_

**Comment by machawk1** [comment]
Travis-CI supports Python 3.8 per their [Building a Python Project](https://docs.travis-ci.com/user/languages/python/) docs, so we could make that move for testing purposes than gradually transition to using any of the language's new features despite homebrew's support (which should not be a barrier).

**Comment by ibnesayeed** [comment]
This reminds me of matrix setup of testing environments in GitHub Workflow, we might want to leverage that.

**Comment by machawk1** [comment]
@ibnesayeed I agree. I have not worked with GitHub Workflow but use a Matrix setup with TravisCI in WAIL ([project's .travis.yml](https://github.com/machawk1/wail/blob/osagnostic/.travis.yml).

**Comment by ibnesayeed** [comment]
I have used it in [accesslog-parse](https://github.com/oduwsdl/accesslog-parser/blob/master/.github/workflows/test.yml)'s test workflow.

**Comment by ibnesayeed** [comment]
I think this ticket can be closed now.
