### ISSUE TITLE
Latest master is not StandardJS compliant

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#626]
Building the Docker image reports errors from StandardJS:
```bash
standard: Use JavaScript Standard Style (https://standardjs.com)
standard: Run `standard --fix` to automatically fix some problems.
  /private/tmp/ipwb/ipwb/assets/webui.js:33:29: ["title"] is better written in dot notation.
  /private/tmp/ipwb/ipwb/assets/webui.js:35:37: ["datetime"] is better written in dot notation.
  /private/tmp/ipwb/ipwb/assets/webui.js:40:68: ["datetime"] is better written in dot notation.
  /private/tmp/ipwb/ipwb/assets/webui.js:45:44: ["mime"] is better written in dot notation.
  /private/tmp/ipwb/ipwb/assets/webui.js:46:46: ["status"] is better written in dot notation.
  /private/tmp/ipwb/ipwb/assets/webui.js:49:35: ["mime"] is better written in dot notation.
  /private/tmp/ipwb/ipwb/assets/webui.js:52:35: ["status"] is better written in dot notation.
```
This is due to ipwb installing the latest standardjs instead of some pinned version, per the Dockerfile. This can be replicated by cloning the latest master fcd5781ff72b77c035087deafd422fb403bd230b , installing `standard` via npm, and running the command `standard` in the root of the working directory.

**Comment by ibnesayeed** [comment]
Sometimes this type of *pseudo-standard* adherence is painful. While i personally prefer using the dot-notation, but if there is an object that has some properties that have spaces or other special characters not suitable for dot notation then I would use the bracket notation for all of them for uniformity sake.

**Comment by machawk1** [comment]
@ibnesayeed Do you believe we should comply or add an exception to the eslint config file?

**Comment by ibnesayeed** [comment]
We can comply with this one as I believe we do not have any properties in this object that would be not friendly to dot notation. Adding exceptions is another unnecessary baggage to carry. I was expressing my views in general.
