### ISSUE TITLE
Remove ServiceWorker and Custom Elements message from README

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#632]
The README states:

> Both Service Worker and Custom Element APIs are new and only supported in modern web browsers (e.g., Chrome > v67, Firefox > v63).

Since ipwb's inception, support for these two techs have become largely ubiquitous in all major browsers except for [Safari/Custom Elements and some mobile browsers per CanIUse](https://caniuse.com/#search=custom%20elements). I think this message should be removed from the README _except_ that I also believe we should document and note exceptions and non-functioning behavior in the browsers where these two techs are not completed to the extent ipwb uses them.

**Comment by machawk1** [comment]
ServiceWorkers seems to have better support now but ipwb seems to assume that the browser supports Custom Elements in `reconstructive-banner.js` with `customElements.define('reconstructive-banner', ReconstructiveBanner);`. In the SW case, we report the lack of support via the console, which is often inaccessible in mobile browsers where the issue is exhibited.

Mobile Safari (default browser for iOS) and the desktop-based Safari (default macOS browser) still do not fully support Custom Elements v1. This is a bit more difficult to determine the impact on iOS, but here is a task relevant to this issue:

- [ ] Evaluate ipwb replay on Apple Safari (desktop) to determine the extent to which lack of complete Custom Elements support has on the replay experience.

I will self-assign this, @ibnesayeed, given our respective OS preferences, but following this evaluation and some elegant handling for Safari users, we might be clear to remove this from the README.

**Comment by ibnesayeed** [comment]
The kind of CustomElements we are using should be supported in Safari's recent versions. The "Customized built-in elements" is not supported in Safari, but we are not using that. That said, please test it and update here with your findings.

**Comment by machawk1** [comment]
I did a quick test in Safari 13.1 on macOS 10.15.4 using `samples/warcs/IAH-20080430204825-00000-blackbook.warc.gz` and the floating banner appears and is usable.

![Screen Shot 2020-06-23 at 10 42 12 AM](https://user-images.githubusercontent.com/2514780/85418104-624c7880-b53e-11ea-88be-b2967290e834.png)

We can likely remove the message relating to the Custom Elements and Service Worker requirements from the README.
