### ISSUE TITLE
Issues when using go-ipfs 0.5.0

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#638]
In anticipation of the 0.5.0 release of go-ipfs, I tested the current master (ipwb v0.2020.04.24.1847 release) against the latest prerelease of ipfs (ipfs version 0.5.0-rc3) with latest ipfshttpclient (ipfshttpclient==0.4.13.2).

In a virtualenv with Python 3.7/3.8:

```bash
> ipwb index samples/warcs/5mementos.warc
Unknown error in retrieving daemon status
<class 'ipfshttpclient.exceptions.StatusError'>
```

In its README, ipfshttpclient (nee the ipfsapi Python module) states it is tested against go-ipfs v0.5.0-rc2. Repeating the above with this version produces the same error.

**Comment by machawk1** [comment]
Testing against latest RC (0.5.0-rc4) seems to be attribute to a change in ipfshttpclient:

```py
import ipfshttpclient
x = ipfshttpclient.Client('/dns/localhost/tcp/5001/http')
x.id()
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ipfshttpclient/http.py", line 266, in _do_raise_for_status
    response.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 405 Client Error: Method Not Allowed for url: http://localhost:5001/api/v0/id?stream-channels=true

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ipfshttpclient/client/base.py", line 15, in wrapper
    result = func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ipfshttpclient/client/miscellaneous.py", line 89, in id
    return self._client.request('/id', args, decoder='json', **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ipfshttpclient/http.py", line 51, in wrapper
    return func(self, *args, **merged)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ipfshttpclient/http.py", line 385, in request
    res = self._request(method, url, params, stream, files, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ipfshttpclient/http.py", line 307, in _request
    self._do_raise_for_status(res)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ipfshttpclient/http.py", line 286, in _do_raise_for_status
    six.raise_from(exceptions.StatusError(error), error)
  File "<string>", line 3, in raise_from
ipfshttpclient.exceptions.StatusError: HTTPError: 405 Client Error: Method Not Allowed for url: http://localhost:5001/api/v0/id?stream-channels=true
```

This is called to determine whether the IPFS daemon is accessible:
https://github.com/oduwsdl/ipwb/blob/4adb8bdd58d400c238128c180c0b121b7a4abd1b/ipwb/util.py#L62-L65
...with the expectation of an exception being thrown if not. In this case, the `ipfshttpclient.exceptions.StatusError` is not explicitly caught but the generic `Exception` catches the fall-through, which is not ideal. We should catch this exception specifically but more importantly:

- [ ] Is there a better way to check from the client whether the daemon is accessible?
- [ ] Was `id()` on a client object in ipfshttpclient deprecated recently?

**Comment by machawk1** [comment]
[v0.5.0 has been released](https://blog.ipfs.io/2020-04-28-go-ipfs-0-5-0/). The above needs re-verification to see if the issue remains and if so, it will need to be resolved ASAP.

**Comment by machawk1** [comment]
I thought maybe it was the path we are using for the API endpoint of `/dns/localhost/tcp/5001/http` but this looks consistent between the versions.

go-ipfs v0.5.0 launch:
```
Swarm listening on /ip4/192.168.1.155/tcp/4001
Swarm listening on /ip4/192.168.1.167/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/192.168.1.155/tcp/4001
Swarm announcing /ip4/192.168.1.167/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
WebUI: http://127.0.0.1:5001/webui
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Daemon is ready
```
go-ipfs v0.4.23:
```
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/192.168.1.155/tcp/4001
Swarm listening on /ip4/192.168.1.167/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip4/100.34.119.17/tcp/4001
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/192.168.1.155/tcp/4001
Swarm announcing /ip4/192.168.1.167/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
WebUI: http://127.0.0.1:5001/webui
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Daemon is ready
```

**Comment by machawk1** [comment]
There is probably a better way to test daemon accessibility since this fails. Let's investigate that for the time being to remedy this issue to be usable with the latest go-ipfs.

Can you document your second point in a separate GitHub issue, @ibnesayeed? I am not understanding the details and it might be out-of-scope here.

**Comment by ibnesayeed** [comment]
This might work if we include the master branch of the ipfshttpclient API instead of the latest release version as per https://github.com/ipfs-shipyard/py-ipfs-http-client/pull/210 and https://github.com/ipfs-shipyard/py-ipfs-http-client/issues/204.

**Comment by ibnesayeed** [comment]
Do we want a temporary fix before the new version of the `ipfshttpclient` is released? If so, I can create a PR.

**Comment by machawk1** [comment]
@ibnesayeed Yes, please submit a PR to get this fixed and compatible with the latest version of go-ipfs.

**Comment by ki4jgt** [comment]
@machawk1 still having issues with this through IPFS Desktop.

**Comment by ibnesayeed** [comment]
@ki4jgt are you running the latest version of IPWB?

**Comment by machawk1** [comment]
@ki4jgt Please do clarify. We moved to a separate Pypi entry for ipwb since there have been delays in ipfshttpclient (the Python IPFS API module) releasing a new version. The latest ipwb is based on a more recent master branch that related to some of the recent changes in go-ipfs (~0.5).

**Comment by ki4jgt** [comment]
I apologize guys. Clicked on the first link on Google with my issue and assumed it was for IPFS.

**Comment by machawk1** [comment]
No problem, @ki4jgt. Good luck on finding your solution and feel free to stop by if you every have a chance to give ipwb a try. 😊
