### ISSUE TITLE
PyTest marker warnings

### ISSUE THREAD

**Issue by ibnesayeed** [oduwsdl/ipwb#651]
Recent versions of PyTest want markers to be declared explicitly, otherwise it generates warnings on them as illustrated below:

```
ipwb/ipwb/tests/test_indexing.py:10: PytestUnknownMarkWarning: Unknown pytest.mark.ipwbIndexerRecordCount - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
```

**Comment by machawk1** [comment]
This can resolved one of two ways, creating a `pytest.ini` file with contents like:

```
[pytest]
ipwbIndexerRecordCount: Praesent tempus euismod molestie.
ipwbIndexerBrokenWARCRecord: Sed gravida pulvinar quam sit.
```

or simply removing the marks altogether. I think they were originally added to give some semantics to the tests but they seem to be redundant of the function names. Is there a purpose for or a reason to retain these marks? Which would you prefer, @ibnesayeed?

**Comment by ibnesayeed** [comment]
I don't see the usefulness of random marker names. These things are usually defined to add metadata for grouping and targeting specific set of tests. I used the built-in `parametrize` marker top run the same test multiple times with supplied set of parameters, which helps DRY tests.

**Comment by machawk1** [comment]
> I don't see the usefulness of random marker names.

I have used these marker names to call specific tests to be executed with pytest without having to execute the whole suite. Is there a better way to do this, @ibnesayeed?

**Comment by ibnesayeed** [comment]
There are various ways to select one or more test cases to run. Custom markers are one way to group tests, but we can do so without that too. However, if we do choose to define custom markers, then we should think in terms of some sort of grouping, instead of unique markers for each test. And whatever markers we choose to add, should be defined. [Read more about it in docs](https://docs.pytest.org/en/stable/example/markers.html) and make an informed decision whether or not we want to use it.

**Comment by machawk1** [comment]
@ibnesayeed If we group tests and groups are lengthy, other than markers, is there a way to run one specific test? I will investigate this further. Having tests is better than not and any process, if effective, is better than no process, even if inefficient.

**Comment by ibnesayeed** [comment]
If you read that article I linked, you will find that you can run tests by their names or even using search terms that will be matched against test function names.

**Comment by machawk1** [comment]
@ibnesayeed Thanks for the link! I knew of the by-name usage but not search terms. Do you believe we should remove the markers currently present and take a different approach (e.g., by-name) when testing individual tests or groups of tests? There are only a few and they seem to be mostly redundant of the function name.

**Comment by ibnesayeed** [comment]
Yes, I do think we should remove these per-test-case custom markers. If in the future we find a need, we will add markers to categorize tests, but will also declare them to avoid warnings.
