### ISSUE TITLE
dataclasses is overlooked in requirements.txt

### ISSUE THREAD

**Issue by TakashiMatsuda** [oduwsdl/ipwb#655]
# Situation
dataclasses is overlooked in requirements.txt.
dataclasses is used here:
https://github.com/oduwsdl/ipwb/blob/eb3a26915e7499bbaa91161bd9a2b7d720c9f6d9/ipwb/backends.py#L1

log: 
```
$ git show
commit eb3a26915e7499bbaa91161bd9a2b7d720c9f6d9 (HEAD -> master, origin/master, origin/HEAD)
Merge: 4bac5b1 f4fe811
Author: Mat Kelly <me@matkelly.com>
Date:   Tue May 19 16:26:01 2020 -0400

    Merge pull request #654 from oduwsdl/issue-630

    Utilize GH Workflow to publish to PyPI
$ pip install -r requirements.txt
$ pip install ./
$ ipwb index samples/warcs/salam-home.warc
Traceback (most recent call last):
  File "/home/takashi/.local/bin/ipwb", line 5, in <module>
    from ipwb.__main__ import main
  File "/home/takashi/.local/lib/python3.6/site-packages/ipwb/__main__.py", line 10, in <module>
    from . import replay
  File "/home/takashi/.local/lib/python3.6/site-packages/ipwb/replay.py", line 38, in <module>
    from .backends import get_web_archive_index
  File "/home/takashi/.local/lib/python3.6/site-packages/ipwb/backends.py", line 1, in <module>
    import dataclasses
ModuleNotFoundError: No module named 'dataclasses'
```

**Comment by ibnesayeed** [comment]
@TakashiMatsuda we decided to only support Python 3.7+ in which `dataclasses` was added in the core. The documentation around supported versions might be inconsistent for now though. If there are situations where we must support 3.6, then we will have to conditionally include it, which will be a messy situation.

**Comment by TakashiMatsuda** [comment]
@ibnesayeed  Thank you for your comment, I got the status. It's no problem to me that only Python 3.7+ is supported. I'll close this issue.

**Comment by ibnesayeed** [comment]
Please let us know if you have any issues running it in 3.7 or 3.8.
