### ISSUE TITLE
Flask dependency is not installed from pip

### ISSUE THREAD

**Issue by ibnesayeed** [oduwsdl/ipwb#67]
```
$ docker run -it --rm python:2.7 bash
$ pip install ipwb
$ ipwb
Traceback (most recent call last):
  File "/usr/local/bin/ipwb", line 7, in <module>
    from ipwb.__main__ import main
  File "/usr/local/lib/python2.7/site-packages/ipwb/__main__.py", line 6, in <module>
    import replay
  File "/usr/local/lib/python2.7/site-packages/ipwb/replay.py", line 13, in <module>
    from flask import Flask
ImportError: No module named flask
```

**Comment by machawk1** [comment]
Potentially due to the dependency being in requirements.txt but not in setup.py. Dependencies should not be in setup.py. Let's try removing it all-together from there and see if dependency resolution still works when install w/ pip via pypi.

**Comment by machawk1** [comment]
Removed from setup.py, purged system, and installed through online pip. Flask does not appear to be installed despite requirements.txt specifying it as a dependency/

**Comment by machawk1** [comment]
761f0396e69998d0408b096c84482f1402da2323 completely removed install_requires and flask was not installed. Explicitly added it to setup.py in 99a767c48adb8cf7389797a3c95ffe4ca168a2a5 and now no complaints when installing from pip online. Strangely, we do not specify pycrypto in the setup.py (but do in requirements.txt) and yet IT is installed but not flask, which is also defined there. Closing this ticket but would like to only have to define reqs in 1 place.

**Comment by machawk1** [comment]
Also, @ibnesayeed, please test this using Docker to ensure the deps are installed. I have done so on two dirty systems.

**Comment by ibnesayeed** [comment]
Dependencies are being installed properly now so this issue can be closed.. However, I think the bare `ipwb` command should show the help as it would if `ipwb -h` was invoked. Currently, it is giving a usage line and an error saying, "ipwb: error: too few arguments".

**Comment by machawk1** [comment]
@ibnesayeed I agree. That should be a separate ticket. Please detail what you expect in another GitHub issue.
