### ISSUE TITLE
README should list complete help output

### ISSUE THREAD

**Issue by ibnesayeed** [oduwsdl/ipwb#68]
Adding output of the CLI help would allow users to understand all the options that are otherwise not documented and can only be accessible after installing the binary.

**Comment by machawk1** [comment]
Wouldn't this become quickly obsolete, @ibnesayeed ? What if we simply provided more guidance to the user to obtain extended options info, akin to https://github.com/ipfs/go-ipfs's usage section?

**Comment by ibnesayeed** [comment]
That's what I meant. There should be a usage section somewhere down below without making it in the way of getting started, but having it in the README would allow users to understand possible options in a nutshell.
