### ISSUE TITLE
README logo is difficult to see in dark mode

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#689]
I noticed that in the GitHub Android app that the project logo is difficult to distinguish from the dark, default background:

![app_logo](https://user-images.githubusercontent.com/2514780/87059180-ff620f00-c1d6-11ea-8cfb-f2b1bb128cb1.png)

This is also likely the case anywhere the background is dark. Per a discussion with @ibnesayeed, one solution is to provide a white stroke to all components of the logo.

**Comment by machawk1** [comment]
Updated provided in `logo-add-stroke` branch but because the URI in the README is absolute and does not use the same domain as github.com, it does not appear in branch README.

**Comment by machawk1** [comment]
Per #690, the logo in the replay web interface will also need to be adjusted. Ideally, the interface would have CSS to read dark mode but currently does not. In an early graphical experiment, simple scaling will be insufficient, as the smaller size of the logo (at least the banner logo) means the smallest stroke of 1px white is too prominent. 1px @ #303030 normal looks ok, but then the image between light and dark mode would have to be different, as the gray stroke is apparent in light mode. This is a task for another issue once the CSS adapts to dark mode but is documented here for future work.

**Comment by ibnesayeed** [comment]
I use Twitter in dark mode, I noticed this issue there as well a few weeks ago. The new image needs to be uploaded in the repository settings so it can appear in social cards too.

**Comment by ibnesayeed** [comment]
With the new image also being larger in size, it appears out of proportion in the README of this repo and PyPI (and perhaps some other places as well).

**Comment by machawk1** [comment]
Re-opening. #690 makes the logo in the README large.

**Comment by ibnesayeed** [comment]
* [x] Updated the social preview image in the repository settings.

**Comment by machawk1** [comment]
Much more subtle version here with #ffffff stroke at 10% opacity.

![logo](https://user-images.githubusercontent.com/2514780/87063487-72ba4f80-c1dc-11ea-9e6b-c6f1295e6368.png)

Keeping it at #ffffff instead of #303030 maintains the color in light mode.

**Comment by machawk1** [comment]
Adjusted a bit more but the smaller lettering on the bottom is not longer as prominent in light mode. See:

* Current master: https://raw.githubusercontent.com/oduwsdl/ipwb/master/docs/logo.png

vs.

* Version without dark mode strokes: https://raw.githubusercontent.com/oduwsdl/ipwb/f813e79862266ff53730f22292c722193e03171e/docs/logo.png

**Comment by machawk1** [comment]
Re-evaluating the PSD, the small lettering is "strong" type. Adjusting the anti-aliasing scheme might provide a better alternate. The four permutations varied only for the small text layer:

Strong:
![logo_strong](https://user-images.githubusercontent.com/2514780/87163906-07cd4f00-c296-11ea-9ca8-950f1110b6a6.png)

Crisp:
![logo_crisp](https://user-images.githubusercontent.com/2514780/87163902-0734b880-c296-11ea-88db-b48523d2173b.png)

Sharp:
![logo_sharp](https://user-images.githubusercontent.com/2514780/87163904-07cd4f00-c296-11ea-826f-4876ba2c7206.png)

Smooth:
![logo_smooth](https://user-images.githubusercontent.com/2514780/87163905-07cd4f00-c296-11ea-8fd0-550a7ec882e8.png)
