### ISSUE TITLE
Allow user to set cdxj path parameter in ipwb replay

### ISSUE THREAD

**Issue by ibnesayeed** [oduwsdl/ipwb#69]
Allow user to pass a parameter to load CDXJ files from for the replay. Currently it is hard coded.

**Comment by machawk1** [comment]
Potentially due to the dependency being in requirements.txt but not in setup.py. Dependencies should not be in setup.py. Let's try removing it all-together from there and see if dependency resolution still works when install w/ pip via pypi.

**Comment by ibnesayeed** [comment]
@machawk1, I think you mixed your thoughts and commented in a different ticket. Also, it is not an installation related matter.

**Comment by machawk1** [comment]
@ibnesayeed Yep, meant for #67. Copied there. Thanks for the sanity check.
