### ISSUE TITLE
Remove superfluous dependency install instruction in README

### ISSUE THREAD

**Issue by ibnesayeed** [oduwsdl/ipwb#703]
I think `pip install ./` should take care of the dependencies as specified in the `setup.py` file, so no need to first run `pip install -r requirements.txt`.

```
$ git clone https://github.com/oduwsdl/ipwb
$ cd ipwb
$ pip install -r requirements.txt
$ pip install ./
```

**Comment by machawk1** [comment]
@ibnesayeed I realize the need for removing redundant dependency specifications but was under the impression that a separate requirements file was the preferred way to go (perhaps implicitly from https://packaging.python.org/discussions/install-requires-vs-requirements/). Open to further discussion prior to removing one method over the other. We might also consult other projects that define a sanctioned well-formed project structure.

**Comment by machawk1** [comment]
Additional caveat to help clarify my understanding: I was under the impression that writing `pip install ./` does not reference the `requirements.txt` file. If so, is that file still needed per #704? Is the requirements file used elsewhere?

**Comment by ibnesayeed** [comment]
I did not suggest removing `requirements.txt` file, that may continue to exist and perhaps we can consolidate test requirements in it too. In this particular case, since we are using `pip` to install the package in the working directory like any other package in a Python package repository, we do not need to run requirements installation separately. We will still use `pip install -r requirements.txt` if we were to run test, or execute Python files directly, not as the `ipwb` command.

**Comment by ibnesayeed** [comment]
> Additional caveat to help clarify my understanding: I was under the impression that writing `pip install ./` does not reference the `requirements.txt` file. If so, is that file still needed per #704? Is the requirements file used elsewhere?

Yes, you are right in thinking that when running `pip install ./` the `requirements.txt` file is not used. As noted above, the file is used when executing Python scripts directly or running tests. We are using in in our Dockerfile to install dependencies before copying all the files to leverage layer caching instead of downloading everything again and again each time any file is changed.

**Comment by machawk1** [comment]
@ibnesayeed If a user clones our repository and runs the three instructions above (and not all 4), will they be able to run the `ipwb` binary?

**Comment by ibnesayeed** [comment]
> @ibnesayeed If a user clones our repository and runs the three instructions above (and not all 4), will they be able to run the `ipwb` command?

YES!

```
$ docker container run --rm -it python:3.8 bash

root@[CID]:/# pip list
Package    Version
---------- -------
pip        20.1.1
setuptools 49.2.0
wheel      0.34.2

root@[CID]:/# git clone https://github.com/oduwsdl/ipwb

root@[CID]:/# cd ipwb

root@[CID]:/ipwb# pip install ./

root@[CID]:/ipwb# pip list
Package        Version
-------------- ----------------
base58         2.0.1
beautifulsoup4 4.9.1
certifi        2020.6.20
chardet        3.0.4
click          7.1.2
Flask          1.1.1
idna           2.10
ipfshttpclient 0.6.0.post1
ipwb           0.2020.7.10.1854
itsdangerous   1.1.0
Jinja2         2.11.2
MarkupSafe     1.1.1
multiaddr      0.0.9
netaddr        0.8.0
pip            20.1.1
pycryptodome   3.9.8
requests       2.24.0
requests-file  1.5.1
setuptools     49.2.0
six            1.11.0
soupsieve      2.0.1
surt           0.3.1
tldextract     2.2.2
urllib3        1.25.10
varint         1.0.2
warcio         1.7.3
Werkzeug       1.0.1
wheel          0.34.2

root@[CID]:/ipwb# ipwb --help
usage: ipwb [-h] [-d DAEMON_ADDRESS] [-v] [-u] {index,replay} ...

InterPlanetary Wayback (ipwb)

optional arguments:
  -h, --help            show this help message and exit
  -d DAEMON_ADDRESS, --daemon DAEMON_ADDRESS
                        Multi-address of IPFS daemon (default /dns/localhost/tcp/5001/http)
  -v, --version         Report the version of ipwb
  -u, --update-check    Check whether an updated version of ipwb is available

ipwb commands:
  Invoke using "ipwb <command>", e.g., ipwb replay <cdxjFile>

  {index,replay}
    index               Index a WARC file for replay in ipwb
    replay              Start the ipwb replay system
```
