### ISSUE TITLE
Update to test with go-ipfs 0.7.0

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#716]
Released September 22, 2020: https://github.com/ipfs/go-ipfs/releases/tag/v0.7.0

**Comment by ibnesayeed** [comment]
I think [py-ipfs-http-client](https://github.com/ipfs-shipyard/py-ipfs-http-client) need to be updated before we can support `0.7.x`.

**Comment by machawk1** [comment]
https://github.com/ipfs-shipyard/py-ipfs-http-client/blob/95337777fdaeecd8850fdd2a51386853fb351575/ipfshttpclient/client/__init__.py#L19 indicates it is supported for their version check. Are there any breaking features in go-ipfs 0.7.0? This might be a question to ask in an issue in the py-ipfs-http-client repo. /cc @ntninja

**Comment by machawk1** [comment]
I mistaken, as is evident in https://travis-ci.org/github/oduwsdl/ipwb/jobs/729743815.

The version check is for < 0.7.0, not ≤ 0.7.0

```
E     ipfshttpclient.exceptions.VersionMismatch: Unsupported daemon version '0.7.0' (not in range: 0.4.22 ≤ … < 0.7.0)
```

**Comment by machawk1** [comment]
- [ ] Bump VERSION_MAXIMUM in `py-ipfs-http-client/client/__init__.py` to 0.7.1, reconfigure dependency to use the modified source for the module, and re-run the tests.

**Comment by ntninja** [comment]
@machawk1: I'm not aware of any breaking changes, but I haven't really looked either. Please give me a couple of days to look into it, before releasing the next version.
