### ISSUE TITLE
Daemon CLI argument not implemented

### ISSUE THREAD

**Issue by gador** [oduwsdl/ipwb#717]
The -d (daemon address) CLI argument isn't implemented, also stated in the help.

I use an external IPFS daemon with an exposed API behind nginx as a reverse proxy. 
Right now it is not possible to use an external Daemon.

**Comment by machawk1** [comment]
@gador Thanks for the report! It was implemented at some point, I believe, but perhaps got refactored out. Thanks for your contribution in #718. @ibnesayeed Can you review the PR?
