### ISSUE TITLE
Input type on web interface is of type "text" when it would be better set to "url"

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#724]
This affects the mobile keyboard displayed. Images below show a photo of a mobile device with a smudged screen exhibiting the two input type, which was required as many mobile devices will hide the keyboard when trying to take a screenshot. PR incoming.

type="text":
![text](https://user-images.githubusercontent.com/2514780/104360752-8d4ce880-54df-11eb-829c-7fbf6fa0854e.jpg)

type="url"
![url](https://user-images.githubusercontent.com/2514780/104360753-8de57f00-54df-11eb-880c-0b89910b8b7e.jpg)

**Comment by ibnesayeed** [comment]
This will perhaps be a good change for now, but in the future if we decide to make it an omnibox to support free-form full-text search keywords or natural language date specifiers, the type will have to be changed back to `text`.

**Comment by machawk1** [comment]
@ibnesayeed I agree and meant to mention this in the ticket. Currently, all this issue/PR does is help with accessibility but ultimately we will want to have something more freeform. I think that goal is far off and not-yet-described in any GitHub issue in this repo as far as I can tell.
