### ISSUE TITLE
Fix the build

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#751]
Without any significant code changes, the test suite has started to report failures. This issue will document what needs to be done to bring it back to a passing state.

**Comment by machawk1** [comment]
One recurring issue reported relates to flask:

```py
ImportError while importing test module '/ipwb/tests/test_replay.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_replay.py:3: in <module>
    from . import testUtil as ipwb_test
tests/testUtil.py:9: in <module>
    from ipwb import replay
ipwb/replay.py:23: in <module>
    from flask import (
/usr/local/lib/python3.10/site-packages/flask/__init__.py:19: in <module>
    from . import json
/usr/local/lib/python3.10/site-packages/flask/json/__init__.py:15: in <module>
    from itsdangerous import json as _json
E   ImportError: cannot import name 'json' from 'itsdangerous' (/usr/local/lib/python3.10/site-packages/itsdangerous/__init__.py)
```

The `itsdangerous` module reports that some json methods were deprecated in version 2.0, released May 2021.

**Comment by machawk1** [comment]
Of all of the permutations only macos-latest, Python 3.7, and ipfs versions 0.9 and 0.11 report failure.

**Comment by machawk1** [comment]
Python 3.7 is still maintained per https://en.wikipedia.org/wiki/History_of_Python , so this can't be written off by removing it from tests just yet.

**Comment by cclauss** [comment]
Is this fixed?

**Comment by machawk1** [comment]
@cclauss The issue seems to come-and-go with GitHub Actions + Python 3.7. I am unable to reliably reproduce it and all are passing at the moment, so I will close this issue for now and re-open it if the issue re-surfaces.
