### ISSUE TITLE
Change default replay port from 5000

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#752]
A recent macOS update uses port 5000 by default for AirPlay Receiving. This is built into the system and turned on by default. While another port could easily be expressed at runtime, let's pick a new default.

**Comment by machawk1** [comment]
@ibnesayeed Is there any opposition to picking a new default port number? If not, can you suggest one that would be appropriate?

**Comment by ibnesayeed** [comment]
This is such an unpleasant behavior by a big company who ignores what has already been used by a popular web server library by default for so long. I think it will be affecting many developers and users of locally running server-based applications that it is not a problem that concerns only us.

That being said, I am okay if we decide to change to a different default port, but we might want to look around and see how others or dealing with this.

**Comment by machawk1** [comment]
As discussed, let's move to use port 2016 as a default. https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers does not have an entry for this value though list a very crowded port 5000. Any issues in moving forward with this @ibnesayeed?

**Comment by ibnesayeed** [comment]
Let's go for it!

**Comment by machawk1** [comment]
PR #758 is ready for your review, @ibnesayeed
