### ISSUE TITLE
Reconstructive banner continues to use old port for hostname

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#759]
In #758 we moved to start using port 2016 instead of port 5000 because of conflicts. When viewing a memento, and pressing the "previous memento" button the banner, the URL still include port 5000.

I checked this with a separate browser to account for potential caching issues.

**Comment by machawk1** [comment]
![5000](https://user-images.githubusercontent.com/2514780/161626117-c1fae0d5-c223-4655-b9f4-a399282fad28.png)

Ideas on where this value might be originating, @ibnesayeed? I am able to reproduce in Chrome, Firefox, and Safari.

**Comment by ibnesayeed** [comment]
Please check the `Link` header of the memento response.

**Comment by machawk1** [comment]
![5000b](https://user-images.githubusercontent.com/2514780/161626907-1dc29707-f982-4b43-8db8-ddcd368d8ea0.png)

Yep, it's there, too. I am thinking it might be reading the Flask default port and not the port from the host.

**Comment by ibnesayeed** [comment]
It is likely coming from the config file that is stored on disk.

**Comment by machawk1** [comment]
That is correct! I just encountered where the code reads the config as the source, which is likely cached from a previous instance.

**Comment by machawk1** [comment]
![5000c](https://user-images.githubusercontent.com/2514780/161627554-99e3a44e-36e7-45a3-8154-b76af13e23c0.png)

**Comment by machawk1** [comment]
Clearing the cached ipwb fixed this issue.
