### ISSUE TITLE
Redirecting the indexer using > may cause "ipfs version XXXX" to be at the beginning of file

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#84]
I'm not sure where this was introduced but would make the cdxj invalid

**Comment by ibnesayeed** [comment]
@machawk1 perhaps we can print that error on STDERR rather than NULL device.

**Comment by machawk1** [comment]
@ibnesayeed The idea with this was to simply invoke the go-ipfs binary without side effects. By checking the version, an exception would be raised (and appropriately caught) if the ipfs binary is not installed. There might be a better way to check if a binary is installed instead of invoking it with the `--version` flag but this solution fit the bill.

**Comment by ibnesayeed** [comment]
In Python 3 there is a method called [shutil.which](https://docs.python.org/dev/library/shutil.html#shutil.which) that behaves like the Unix `which` command. In Python 2 [find_executable](http://epydoc.sourceforge.net/stdlib/distutils.spawn-module.html) method can be used instead. Calling `subprocess` is costly as it invokes the actual binary of the `ipfs` in one-off mode as a separate process (though, it's not too serious as it only happens in the beginning, but the idiomatic approach should be used instead).

**Comment by machawk1** [comment]
@ibnesayeed I agree. Something more akin to UNIX `which` would be more ideal. The issue with this ticket was the noise introduced, which was far more disastrous. See #87.
